// Icon mapping for bot command categories
export const CATEGORY_ICONS = {
  moderation: "ShieldIcon",
  security: "LockIcon",
  utility: "WrenchIcon",
  server: "ServerIcon",
  fun: "SmileIcon",
  leveling: "TrendingUpIcon", // Fallback for specific engagement sub-types
  giveaway: "GiftIcon",
  logging: "FileTextIcon",
  customization: "PaletteIcon",
  automation: "GearIcon",
  engagement: "ActivityIcon",
  developer: "CodeIcon",
  roles: "UsersIcon",
  channels: "HashIcon",
  tags: "TagIcon",
  welcome: "LogInIcon",
  suggestions: "LightbulbIcon",
  economy: "CoinsIcon",
  music: "MusicIcon",
  fun_games: "Gamepad2Icon",
  admin: "CrownIcon",
  social: "UsersIcon",
  commands: "TerminalIcon",
  all: "CommandsIcon",
};

export const CATEGORY_COLORS = {
  moderation: "from-white/10 to-white/20",
  security: "from-white/10 to-white/20",
  utility: "from-white/10 to-white/20",
  server: "from-white/10 to-white/20",
  fun: "from-white/10 to-white/20",
  leveling: "from-white/10 to-white/20",
  giveaway: "from-white/10 to-white/20",
  logging: "from-white/10 to-white/20",
  customization: "from-white/10 to-white/20",
  automation: "from-white/10 to-white/20",
  engagement: "from-white/10 to-white/20",
  developer: "from-white/10 to-white/20",
  roles: "from-white/10 to-white/20",
  channels: "from-white/10 to-white/20",
  tags: "from-white/10 to-white/20",
  welcome: "from-white/10 to-white/20",
  suggestions: "from-white/10 to-white/20",
  economy: "from-white/10 to-white/20",
  music: "from-white/10 to-white/20",
  fun_games: "from-white/10 to-white/20",
  admin: "from-white/10 to-white/20",
  social: "from-white/10 to-white/20",
};

export const CATEGORY_DESCRIPTIONS = {
  moderation: "Ban, kick, timeout, and manage members",
  security: "Protect your server from attacks and raids",
  utility: "Useful tools and server management",
  server: "Configure server settings and features",
  fun: "Entertainment and games for members",
  leveling: "Member XP and ranking system",
  giveaway: "Create and manage giveaways",
  logging: "Track server events and changes",
  customization: "Customize roles, reactions, and more",
  automation: "Automate tasks and responses",
  engagement: "Keep members engaged and active",
  developer: "Developer and testing commands",
  roles: "Manage roles and permissions",
  channels: "Channel management and controls",
  tags: "Create custom command shortcuts",
  welcome: "Welcome new members automatically",
  suggestions: "Member suggestions system",
  economy: "Economy and currency system",
  music: "Music playback and management",
  fun_games: "Games and entertainment",
  admin: "Admin-only commands",
  social: "Search social media profiles (TikTok, Roblox, etc.)",
};
