// Icon mapping for bot command categories
export const CATEGORY_ICONS = {
  moderation: "Shield",
  security: "Lock",
  utility: "Wrench",
  server: "Settings",
  fun: "Smile",
  leveling: "TrendingUp",
  giveaway: "Gift",
  logging: "FileText",
  customization: "Palette",
  automation: "Zap",
  engagement: "Users",
  developer: "Code",
  roles: "User",
  channels: "Hash",
  tags: "Tag",
  welcome: "LogIn",
  suggestions: "Lightbulb",
  economy: "Coins",
  music: "Music",
  fun_games: "Gamepad2",
  admin: "CrownIcon",
  social: "Share2",
};

export const CATEGORY_COLORS = {
  moderation: "from-red-500 to-red-600",
  security: "from-blue-500 to-blue-600",
  utility: "from-purple-500 to-purple-600",
  server: "from-gray-500 to-gray-600",
  fun: "from-yellow-500 to-yellow-600",
  leveling: "from-green-500 to-green-600",
  giveaway: "from-pink-500 to-pink-600",
  logging: "from-indigo-500 to-indigo-600",
  customization: "from-cyan-500 to-cyan-600",
  automation: "from-orange-500 to-orange-600",
  engagement: "from-teal-500 to-teal-600",
  developer: "from-slate-500 to-slate-600",
  roles: "from-violet-500 to-violet-600",
  channels: "from-lime-500 to-lime-600",
  tags: "from-rose-500 to-rose-600",
  welcome: "from-sky-500 to-sky-600",
  suggestions: "from-amber-500 to-amber-600",
  economy: "from-yellow-500 to-yellow-600",
  music: "from-fuchsia-500 to-fuchsia-600",
  fun_games: "from-red-500 to-pink-600",
  admin: "from-purple-500 to-indigo-600",
  social: "from-blue-400 to-blue-500",
};

export const CATEGORY_DESCRIPTIONS = {
  moderation: "Ban, kick, timeout, and manage members",
  security: "Protect your server from attacks and raids",
  utility: "Useful tools and server management",
  server: "Configure server settings and features",
  fun: "Entertainment and games for members",
  leveling: "Member XP and ranking system",
  giveaway: "Create and manage giveaways",
  logging: "Track server events and changes",
  customization: "Customize roles, reactions, and more",
  automation: "Automate tasks and responses",
  engagement: "Keep members engaged and active",
  developer: "Developer and testing commands",
  roles: "Manage roles and permissions",
  channels: "Channel management and controls",
  tags: "Create custom command shortcuts",
  welcome: "Welcome new members automatically",
  suggestions: "Member suggestions system",
  economy: "Economy and currency system",
  music: "Music playback and management",
  fun_games: "Games and entertainment",
  admin: "Admin-only commands",
  social: "Search social media profiles (TikTok, Roblox, etc.)",
};
