// AUTO-GENERATED: Automation commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  raw_name?: string;
  func_name?: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const AUTOMATION_COMMANDS: Record<string, Command> = {
  "autoreact": {
    "raw_name": "autoreact",
    "func_name": "autoreact",
    "parent_func_name": null,
    "description": "set up auto reactions for messages",
    "aliases": [
      "ar"
    ],
    "category": "automation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "autoreact add",
      "autoreact clear",
      "autoreact list",
      "autoreact matchtype",
      "autoreact remove",
      "autoreact roletrack",
      "autoreact scope",
      "autoreact toggle"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact"
  },
  "autoreact_add": {
    "raw_name": "add",
    "func_name": "autoreact_add",
    "parent_func_name": "autoreact",
    "description": "add a new autoreact rule",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "emojis",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact add <trigger> <emojis>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact add"
  },
  "autoreact_remove": {
    "raw_name": "remove",
    "func_name": "autoreact_remove",
    "parent_func_name": "autoreact",
    "description": "remove an autoreact rule",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "rule_id",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact remove <rule_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact remove"
  },
  "autoreact_list": {
    "raw_name": "list",
    "func_name": "autoreact_list",
    "parent_func_name": "autoreact",
    "description": "show all autoreact rules",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact list"
  },
  "autoreact_clear": {
    "raw_name": "clear",
    "func_name": "autoreact_clear",
    "parent_func_name": "autoreact",
    "description": "clear all autoreact rules",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact clear"
  },
  "autoreact_toggle": {
    "raw_name": "toggle",
    "func_name": "autoreact_toggle",
    "parent_func_name": "autoreact",
    "description": "turn autoreactions on or off",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "enabled",
        "type": "bool"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact toggle <enabled>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact toggle"
  },
  "autoreact_matchtype": {
    "raw_name": "matchtype",
    "func_name": "matchtype",
    "parent_func_name": "autoreact",
    "description": "change how rules match text",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact matchtype"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "autoreact matchtype get",
      "autoreact matchtype list",
      "autoreact matchtype set"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact matchtype"
  },
  "autoreact_matchtype_set": {
    "raw_name": "set",
    "func_name": "matchtype_set",
    "parent_func_name": "matchtype",
    "description": "set how a rule matches text",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "rule_id",
        "type": "int"
      },
      {
        "name": "match_type",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact matchtype set <rule_id> <match_type>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact matchtype set"
  },
  "autoreact_matchtype_get": {
    "raw_name": "get",
    "func_name": "matchtype_get",
    "parent_func_name": "matchtype",
    "description": "check a rule's match type",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "rule_id",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact matchtype get <rule_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact matchtype get"
  },
  "autoreact_matchtype_list": {
    "raw_name": "list",
    "func_name": "matchtype_list",
    "parent_func_name": "matchtype",
    "description": "show rules by match type",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact matchtype list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact matchtype list"
  },
  "autoreact_roletrack": {
    "raw_name": "roletrack",
    "func_name": "roletrack",
    "parent_func_name": "autoreact",
    "description": "react to messages from specific roles",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "autoreact roletrack add",
      "autoreact roletrack bypass",
      "autoreact roletrack emoji",
      "autoreact roletrack list",
      "autoreact roletrack remove",
      "autoreact roletrack restrict"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack"
  },
  "autoreact_roletrack_add": {
    "raw_name": "add",
    "func_name": "roletrack_add",
    "parent_func_name": "roletrack",
    "description": "add reactions when a role messages",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      },
      {
        "name": "emojis",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack add <role> <emojis>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack add"
  },
  "autoreact_roletrack_remove": {
    "raw_name": "remove",
    "func_name": "roletrack_remove",
    "parent_func_name": "roletrack",
    "description": "stop tracking a role",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack remove <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack remove"
  },
  "autoreact_roletrack_list": {
    "raw_name": "list",
    "func_name": "roletrack_list",
    "parent_func_name": "roletrack",
    "description": "show all tracked roles",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack list"
  },
  "autoreact_roletrack_emoji": {
    "raw_name": "emoji",
    "func_name": "roletrack_emoji",
    "parent_func_name": "roletrack",
    "description": "change emojis for a tracked role",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      },
      {
        "name": "emojis",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack emoji <role> <emojis>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack emoji"
  },
  "autoreact_roletrack_restrict": {
    "raw_name": "restrict",
    "func_name": "roletrack_restrict",
    "parent_func_name": "roletrack",
    "description": "only react to users with this role",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack restrict <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack restrict"
  },
  "autoreact_roletrack_bypass": {
    "raw_name": "bypass",
    "func_name": "roletrack_bypass",
    "parent_func_name": "roletrack",
    "description": "let a role skip autoreactions",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact roletrack bypass <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact roletrack bypass"
  },
  "autoreact_scope": {
    "raw_name": "scope",
    "func_name": "scope",
    "parent_func_name": "autoreact",
    "description": "set where rules work",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact scope"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "autoreact scope get",
      "autoreact scope list",
      "autoreact scope set"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact scope"
  },
  "autoreact_scope_set": {
    "raw_name": "set",
    "func_name": "scope_set",
    "parent_func_name": "scope",
    "description": "set where a rule applies",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "rule_id",
        "type": "int"
      },
      {
        "name": "scope_type",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "examples": [
      "!autoreact scope set <rule_id> <scope_type> [target]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact scope set"
  },
  "autoreact_scope_get": {
    "raw_name": "get",
    "func_name": "scope_get",
    "parent_func_name": "scope",
    "description": "check a rule's scope",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [
      {
        "name": "rule_id",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!autoreact scope get <rule_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact scope get"
  },
  "autoreact_scope_list": {
    "raw_name": "list",
    "func_name": "scope_list",
    "parent_func_name": "scope",
    "description": "show rules by scope",
    "aliases": [],
    "category": "automation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!autoreact scope list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\autoreactions.py",
    "name": "autoreact scope list"
  },
  "invoke": {
    "raw_name": "invoke",
    "func_name": "invoke",
    "parent_func_name": null,
    "description": "change what the bot says for mod actions",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "invoke ban",
      "invoke hardban",
      "invoke kick",
      "invoke mute",
      "invoke softban",
      "invoke timeout",
      "invoke unban",
      "invoke unmute",
      "invoke untimeout",
      "invoke variables",
      "invoke warn"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke"
  },
  "invoke_variables": {
    "raw_name": "variables",
    "func_name": "invoke_variables",
    "parent_func_name": "invoke",
    "description": "see all template variables",
    "aliases": [
      "vars",
      "placeholders"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke variables"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke variables"
  },
  "invoke_timeout": {
    "raw_name": "timeout",
    "func_name": "invoke_timeout",
    "parent_func_name": "invoke",
    "description": "timeout message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke timeout"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke timeout dm",
      "invoke timeout dm-view",
      "invoke timeout message",
      "invoke timeout message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke timeout"
  },
  "invoke_timeout_dm": {
    "raw_name": "dm",
    "func_name": "timeout_dm",
    "parent_func_name": "invoke_timeout",
    "description": "set the dm sent for timeouts",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke timeout dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke timeout dm"
  },
  "invoke_timeout_dm-view": {
    "raw_name": "dm-view",
    "func_name": "timeout_dmview",
    "parent_func_name": "invoke_timeout",
    "description": "see the timeout dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke timeout dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke timeout dm-view"
  },
  "invoke_timeout_message-view": {
    "raw_name": "message-view",
    "func_name": "timeout_messageview",
    "parent_func_name": "invoke_timeout",
    "description": "see the timeout server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke timeout message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke timeout message-view"
  },
  "invoke_timeout_message": {
    "raw_name": "message",
    "func_name": "timeout_message",
    "parent_func_name": "invoke_timeout",
    "description": "set the server message for timeouts",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke timeout message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke timeout message"
  },
  "invoke_kick": {
    "raw_name": "kick",
    "func_name": "invoke_kick",
    "parent_func_name": "invoke",
    "description": "kick message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke kick"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke kick dm",
      "invoke kick dm-view",
      "invoke kick message",
      "invoke kick message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke kick"
  },
  "invoke_kick_dm": {
    "raw_name": "dm",
    "func_name": "kick_dm",
    "parent_func_name": "invoke_kick",
    "description": "set the dm sent for kicks",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke kick dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke kick dm"
  },
  "invoke_kick_dm-view": {
    "raw_name": "dm-view",
    "func_name": "kick_dmview",
    "parent_func_name": "invoke_kick",
    "description": "see the kick dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke kick dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke kick dm-view"
  },
  "invoke_kick_message": {
    "raw_name": "message",
    "func_name": "kick_message",
    "parent_func_name": "invoke_kick",
    "description": "set the server message for kicks",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke kick message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke kick message"
  },
  "invoke_kick_message-view": {
    "raw_name": "message-view",
    "func_name": "kick_messageview",
    "parent_func_name": "invoke_kick",
    "description": "see the kick server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke kick message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke kick message-view"
  },
  "invoke_softban": {
    "raw_name": "softban",
    "func_name": "invoke_softban",
    "parent_func_name": "invoke",
    "description": "softban message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke softban"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke softban dm",
      "invoke softban dm-view",
      "invoke softban message",
      "invoke softban message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke softban"
  },
  "invoke_softban_dm": {
    "raw_name": "dm",
    "func_name": "softban_dm",
    "parent_func_name": "invoke_softban",
    "description": "set the dm sent for softbans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke softban dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke softban dm"
  },
  "invoke_softban_dm-view": {
    "raw_name": "dm-view",
    "func_name": "softban_dmview",
    "parent_func_name": "invoke_softban",
    "description": "see the softban dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke softban dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke softban dm-view"
  },
  "invoke_softban_message": {
    "raw_name": "message",
    "func_name": "softban_message",
    "parent_func_name": "invoke_softban",
    "description": "set the server message for softbans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke softban message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke softban message"
  },
  "invoke_softban_message-view": {
    "raw_name": "message-view",
    "func_name": "softban_messageview",
    "parent_func_name": "invoke_softban",
    "description": "see the softban server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke softban message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke softban message-view"
  },
  "invoke_hardban": {
    "raw_name": "hardban",
    "func_name": "invoke_hardban",
    "parent_func_name": "invoke",
    "description": "hardban message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke hardban"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke hardban message",
      "invoke hardban message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke hardban"
  },
  "invoke_hardban_message": {
    "raw_name": "message",
    "func_name": "hardban_message",
    "parent_func_name": "invoke_hardban",
    "description": "set the server message for hardbans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke hardban message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke hardban message"
  },
  "invoke_hardban_message-view": {
    "raw_name": "message-view",
    "func_name": "hardban_messageview",
    "parent_func_name": "invoke_hardban",
    "description": "see the hardban server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke hardban message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke hardban message-view"
  },
  "invoke_unban": {
    "raw_name": "unban",
    "func_name": "invoke_unban",
    "parent_func_name": "invoke",
    "description": "unban message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unban"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke unban dm",
      "invoke unban dm-view",
      "invoke unban message",
      "invoke unban message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unban"
  },
  "invoke_unban_dm": {
    "raw_name": "dm",
    "func_name": "unban_dm",
    "parent_func_name": "invoke_unban",
    "description": "set the dm sent for unbans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke unban dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unban dm"
  },
  "invoke_unban_dm-view": {
    "raw_name": "dm-view",
    "func_name": "unban_dmview",
    "parent_func_name": "invoke_unban",
    "description": "see the unban dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unban dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unban dm-view"
  },
  "invoke_unban_message": {
    "raw_name": "message",
    "func_name": "unban_message",
    "parent_func_name": "invoke_unban",
    "description": "set the server message for unbans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke unban message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unban message"
  },
  "invoke_unban_message-view": {
    "raw_name": "message-view",
    "func_name": "unban_messageview",
    "parent_func_name": "invoke_unban",
    "description": "see the unban server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unban message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unban message-view"
  },
  "invoke_unmute": {
    "raw_name": "unmute",
    "func_name": "invoke_unmute",
    "parent_func_name": "invoke",
    "description": "unmute message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unmute"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke unmute dm",
      "invoke unmute dm-view",
      "invoke unmute message",
      "invoke unmute message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unmute"
  },
  "invoke_unmute_dm": {
    "raw_name": "dm",
    "func_name": "unmute_dm",
    "parent_func_name": "invoke_unmute",
    "description": "set the dm sent for unmutes",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke unmute dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unmute dm"
  },
  "invoke_unmute_dm-view": {
    "raw_name": "dm-view",
    "func_name": "unmute_dmview",
    "parent_func_name": "invoke_unmute",
    "description": "see the unmute dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unmute dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unmute dm-view"
  },
  "invoke_unmute_message": {
    "raw_name": "message",
    "func_name": "unmute_message",
    "parent_func_name": "invoke_unmute",
    "description": "set the server message for unmutes",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke unmute message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unmute message"
  },
  "invoke_unmute_message-view": {
    "raw_name": "message-view",
    "func_name": "unmute_messageview",
    "parent_func_name": "invoke_unmute",
    "description": "see the unmute server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke unmute message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke unmute message-view"
  },
  "invoke_mute": {
    "raw_name": "mute",
    "func_name": "invoke_mute",
    "parent_func_name": "invoke",
    "description": "mute message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke mute"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke mute dm",
      "invoke mute dm-view",
      "invoke mute message",
      "invoke mute message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke mute"
  },
  "invoke_mute_dm": {
    "raw_name": "dm",
    "func_name": "mute_dm",
    "parent_func_name": "invoke_mute",
    "description": "set the dm sent for mutes",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke mute dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke mute dm"
  },
  "invoke_mute_dm-view": {
    "raw_name": "dm-view",
    "func_name": "mute_dmview",
    "parent_func_name": "invoke_mute",
    "description": "see the mute dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke mute dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke mute dm-view"
  },
  "invoke_mute_message": {
    "raw_name": "message",
    "func_name": "mute_message",
    "parent_func_name": "invoke_mute",
    "description": "set the server message for mutes",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke mute message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke mute message"
  },
  "invoke_mute_message-view": {
    "raw_name": "message-view",
    "func_name": "mute_messageview",
    "parent_func_name": "invoke_mute",
    "description": "see the mute server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke mute message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke mute message-view"
  },
  "invoke_ban": {
    "raw_name": "ban",
    "func_name": "invoke_ban",
    "parent_func_name": "invoke",
    "description": "ban message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke ban"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke ban dm",
      "invoke ban dm-view",
      "invoke ban message",
      "invoke ban message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke ban"
  },
  "invoke_ban_dm": {
    "raw_name": "dm",
    "func_name": "ban_dm",
    "parent_func_name": "invoke_ban",
    "description": "set the dm sent for bans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke ban dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke ban dm"
  },
  "invoke_ban_dm-view": {
    "raw_name": "dm-view",
    "func_name": "ban_dmview",
    "parent_func_name": "invoke_ban",
    "description": "see the ban dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke ban dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke ban dm-view"
  },
  "invoke_ban_message": {
    "raw_name": "message",
    "func_name": "ban_message",
    "parent_func_name": "invoke_ban",
    "description": "set the server message for bans",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke ban message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke ban message"
  },
  "invoke_ban_message-view": {
    "raw_name": "message-view",
    "func_name": "ban_messageview",
    "parent_func_name": "invoke_ban",
    "description": "see the ban server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke ban message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke ban message-view"
  },
  "invoke_warn": {
    "raw_name": "warn",
    "func_name": "invoke_warn",
    "parent_func_name": "invoke",
    "description": "warn message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke warn"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke warn dm",
      "invoke warn dm-view",
      "invoke warn message",
      "invoke warn message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke warn"
  },
  "invoke_warn_dm": {
    "raw_name": "dm",
    "func_name": "warn_dm",
    "parent_func_name": "invoke_warn",
    "description": "set the dm sent for warns",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke warn dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke warn dm"
  },
  "invoke_warn_dm-view": {
    "raw_name": "dm-view",
    "func_name": "warn_dmview",
    "parent_func_name": "invoke_warn",
    "description": "see the warn dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke warn dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke warn dm-view"
  },
  "invoke_warn_message": {
    "raw_name": "message",
    "func_name": "warn_message",
    "parent_func_name": "invoke_warn",
    "description": "set the server message for warns",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke warn message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke warn message"
  },
  "invoke_warn_message-view": {
    "raw_name": "message-view",
    "func_name": "warn_messageview",
    "parent_func_name": "invoke_warn",
    "description": "see the warn server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke warn message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke warn message-view"
  },
  "invoke_untimeout": {
    "raw_name": "untimeout",
    "func_name": "invoke_untimeout",
    "parent_func_name": "invoke",
    "description": "untimeout message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke untimeout"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "invoke untimeout dm",
      "invoke untimeout dm-view",
      "invoke untimeout message",
      "invoke untimeout message-view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke untimeout"
  },
  "invoke_untimeout_dm": {
    "raw_name": "dm",
    "func_name": "untimeout_dm",
    "parent_func_name": "invoke_untimeout",
    "description": "set the dm sent for untimeouts",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke untimeout dm [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke untimeout dm"
  },
  "invoke_untimeout_dm-view": {
    "raw_name": "dm-view",
    "func_name": "untimeout_dmview",
    "parent_func_name": "invoke_untimeout",
    "description": "see the untimeout dm",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke untimeout dm-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke untimeout dm-view"
  },
  "invoke_untimeout_message": {
    "raw_name": "message",
    "func_name": "untimeout_message",
    "parent_func_name": "invoke_untimeout",
    "description": "set the server message for untimeouts",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!invoke untimeout message [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke untimeout message"
  },
  "invoke_untimeout_message-view": {
    "raw_name": "message-view",
    "func_name": "untimeout_messageview",
    "parent_func_name": "invoke_untimeout",
    "description": "see the untimeout server message",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!invoke untimeout message-view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\invoke.py",
    "name": "invoke untimeout message-view"
  },
  "triggers": {
    "raw_name": "triggers",
    "func_name": "triggers_group",
    "parent_func_name": null,
    "description": "auto response triggers",
    "aliases": [
      "trigger"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "triggers channel",
      "triggers clear",
      "triggers create",
      "triggers disable",
      "triggers duplicate",
      "triggers edit",
      "triggers enable",
      "triggers endswith",
      "triggers exact",
      "triggers export",
      "triggers ignore",
      "triggers import",
      "triggers info",
      "triggers list",
      "triggers log",
      "triggers move",
      "triggers regex",
      "triggers remove",
      "triggers rename",
      "triggers search",
      "triggers startswith",
      "triggers stats",
      "triggers strict",
      "triggers toggle",
      "triggers unignore"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers"
  },
  "triggers_list": {
    "raw_name": "list",
    "func_name": "triggers_list",
    "parent_func_name": "triggers_group",
    "description": "show all triggers",
    "aliases": [
      "ls"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers list"
  },
  "triggers_create": {
    "raw_name": "create",
    "func_name": "triggers_create",
    "parent_func_name": "triggers_group",
    "description": "create a new trigger",
    "aliases": [
      "add"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers create <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers create"
  },
  "triggers_strict": {
    "raw_name": "strict",
    "func_name": "triggers_strict",
    "parent_func_name": "triggers_group",
    "description": "create a case-sensitive trigger",
    "aliases": [
      "s"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers strict <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers strict"
  },
  "triggers_exact": {
    "raw_name": "exact",
    "func_name": "triggers_exact",
    "parent_func_name": "triggers_group",
    "description": "create a trigger that matches exactly",
    "aliases": [
      "e"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers exact <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers exact"
  },
  "triggers_startswith": {
    "raw_name": "startswith",
    "func_name": "triggers_startswith",
    "parent_func_name": "triggers_group",
    "description": "trigger when message starts with text",
    "aliases": [
      "sw"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers startswith <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers startswith"
  },
  "triggers_endswith": {
    "raw_name": "endswith",
    "func_name": "triggers_endswith",
    "parent_func_name": "triggers_group",
    "description": "trigger when message ends with text",
    "aliases": [
      "ew"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers endswith <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers endswith"
  },
  "triggers_regex": {
    "raw_name": "regex",
    "func_name": "triggers_regex",
    "parent_func_name": "triggers_group",
    "description": "create a trigger using regex",
    "aliases": [
      "re"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers regex <trigger> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers regex"
  },
  "triggers_remove": {
    "raw_name": "remove",
    "func_name": "triggers_remove",
    "parent_func_name": "triggers_group",
    "description": "delete a trigger",
    "aliases": [
      "rm",
      "delete"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers remove <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers remove"
  },
  "triggers_clear": {
    "raw_name": "clear",
    "func_name": "triggers_clear",
    "parent_func_name": "triggers_group",
    "description": "delete all triggers",
    "aliases": [
      "deleteall"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers clear"
  },
  "triggers_channel": {
    "raw_name": "channel",
    "func_name": "triggers_channel",
    "parent_func_name": "triggers_group",
    "description": "create a trigger for a specific channel",
    "aliases": [
      "ch"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "channel",
        "type": "TextChannel"
      },
      {
        "name": "response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers channel <trigger> <channel> <response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers channel"
  },
  "triggers_ignore": {
    "raw_name": "ignore",
    "func_name": "triggers_ignore",
    "parent_func_name": "triggers_group",
    "description": "ignore triggers for a user or channel",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers ignore <target>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers ignore"
  },
  "triggers_unignore": {
    "raw_name": "unignore",
    "func_name": "triggers_unignore",
    "parent_func_name": "triggers_group",
    "description": "stop ignoring a user or channel",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers unignore <target>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers unignore"
  },
  "triggers_edit": {
    "raw_name": "edit",
    "func_name": "triggers_edit",
    "parent_func_name": "triggers_group",
    "description": "change a trigger's response",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "new_response",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers edit <trigger> <new_response>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers edit"
  },
  "triggers_info": {
    "raw_name": "info",
    "func_name": "triggers_info",
    "parent_func_name": "triggers_group",
    "description": "see details about a trigger",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers info <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers info"
  },
  "triggers_enable": {
    "raw_name": "enable",
    "func_name": "triggers_enable",
    "parent_func_name": "triggers_group",
    "description": "turn on a trigger",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers enable <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers enable"
  },
  "triggers_disable": {
    "raw_name": "disable",
    "func_name": "triggers_disable",
    "parent_func_name": "triggers_group",
    "description": "turn off a trigger",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers disable <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers disable"
  },
  "triggers_move": {
    "raw_name": "move",
    "func_name": "triggers_move",
    "parent_func_name": "triggers_group",
    "description": "move a trigger to another channel",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers move <trigger> <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers move"
  },
  "triggers_rename": {
    "raw_name": "rename",
    "func_name": "triggers_rename",
    "parent_func_name": "triggers_group",
    "description": "change a trigger's text",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      },
      {
        "name": "new_name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers rename <trigger> <new_name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers rename"
  },
  "triggers_duplicate": {
    "raw_name": "duplicate",
    "func_name": "triggers_duplicate",
    "parent_func_name": "triggers_group",
    "description": "copy a trigger",
    "aliases": [
      "copy"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers duplicate <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers duplicate"
  },
  "triggers_toggle": {
    "raw_name": "toggle",
    "func_name": "triggers_toggle",
    "parent_func_name": "triggers_group",
    "description": "switch a trigger on or off",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers toggle <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers toggle"
  },
  "triggers_log": {
    "raw_name": "log",
    "func_name": "triggers_log",
    "parent_func_name": "triggers_group",
    "description": "see how often a trigger is used",
    "aliases": [
      "usage"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "trigger",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers log <trigger>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers log"
  },
  "triggers_stats": {
    "raw_name": "stats",
    "func_name": "triggers_stats",
    "parent_func_name": "triggers_group",
    "description": "see trigger stats for this server",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers stats"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers stats"
  },
  "triggers_search": {
    "raw_name": "search",
    "func_name": "triggers_search",
    "parent_func_name": "triggers_group",
    "description": "find triggers by keyword",
    "aliases": [
      "find"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!triggers search <query>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers search"
  },
  "triggers_import": {
    "raw_name": "import",
    "func_name": "triggers_import",
    "parent_func_name": "triggers_group",
    "description": "import triggers from a file",
    "aliases": [
      "restore"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers import"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers import"
  },
  "triggers_export": {
    "raw_name": "export",
    "func_name": "triggers_export",
    "parent_func_name": "triggers_group",
    "description": "save triggers to a file",
    "aliases": [
      "backup"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!triggers export"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\triggers.py",
    "name": "triggers export"
  },
  "greet": {
    "raw_name": "greet",
    "func_name": "greet_prefix",
    "parent_func_name": null,
    "description": "set up welcome and leave messages",
    "aliases": [
      "welcome",
      "wlc"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "greet autorole",
      "greet channel",
      "greet dm",
      "greet leave",
      "greet message",
      "greet test",
      "greet variables"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet"
  },
  "greet_message": {
    "raw_name": "message",
    "func_name": "message_group",
    "parent_func_name": "greet_prefix",
    "description": "set up welcome messages",
    "aliases": [
      "msg"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet message"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet message preview",
      "greet message remove",
      "greet message set"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet message"
  },
  "greet_message_set": {
    "raw_name": "set",
    "func_name": "message_set",
    "parent_func_name": "message_group",
    "description": "set the welcome message",
    "aliases": [
      "setmessage"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet message set <text>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet message set"
  },
  "greet_message_remove": {
    "raw_name": "remove",
    "func_name": "message_remove",
    "parent_func_name": "message_group",
    "description": "delete the welcome message",
    "aliases": [
      "removemessage",
      "delmsg"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet message remove"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet message remove"
  },
  "greet_message_preview": {
    "raw_name": "preview",
    "func_name": "message_preview",
    "parent_func_name": "message_group",
    "description": "see how your welcome message looks",
    "aliases": [
      "previewmsg"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet message preview"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet message preview"
  },
  "greet_channel": {
    "raw_name": "channel",
    "func_name": "channel_group",
    "parent_func_name": "greet_prefix",
    "description": "set where welcome messages go",
    "aliases": [
      "ch"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet channel"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet channel add",
      "greet channel remove"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet channel"
  },
  "greet_channel_add": {
    "raw_name": "add",
    "func_name": "channel_add",
    "parent_func_name": "channel_group",
    "description": "add a welcome channel",
    "aliases": [
      "addchannel",
      "setchannel"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet channel add <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet channel add"
  },
  "greet_channel_remove": {
    "raw_name": "remove",
    "func_name": "channel_remove",
    "parent_func_name": "channel_group",
    "description": "remove a welcome channel",
    "aliases": [
      "removechannel",
      "delchannel"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet channel remove <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet channel remove"
  },
  "greet_dm": {
    "raw_name": "dm",
    "func_name": "dm_group",
    "parent_func_name": "greet_prefix",
    "description": "dm welcome settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet dm"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet dm disable",
      "greet dm enable",
      "greet dm status"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet dm"
  },
  "greet_dm_enable": {
    "raw_name": "enable",
    "func_name": "dm_enable",
    "parent_func_name": "dm_group",
    "description": "send welcome messages via dm",
    "aliases": [
      "enabledm",
      "on"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet dm enable"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet dm enable"
  },
  "greet_dm_disable": {
    "raw_name": "disable",
    "func_name": "dm_disable",
    "parent_func_name": "dm_group",
    "description": "stop sending dm welcomes",
    "aliases": [
      "disabledm",
      "off"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet dm disable"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet dm disable"
  },
  "greet_dm_status": {
    "raw_name": "status",
    "func_name": "dm_status",
    "parent_func_name": "dm_group",
    "description": "check if dm welcomes are on",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet dm status"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet dm status"
  },
  "greet_leave": {
    "raw_name": "leave",
    "func_name": "leave_group",
    "parent_func_name": "greet_prefix",
    "description": "goodbye message settings",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet leave"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet leave channel-add",
      "greet leave channel-remove",
      "greet leave message-preview",
      "greet leave message-remove",
      "greet leave message-set"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave"
  },
  "greet_leave_message-set": {
    "raw_name": "message-set",
    "func_name": "leave_message_set",
    "parent_func_name": "leave_group",
    "description": "set the leave message",
    "aliases": [
      "setleave",
      "leavemsg"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet leave message-set <text>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave message-set"
  },
  "greet_leave_message-remove": {
    "raw_name": "message-remove",
    "func_name": "leave_message_remove",
    "parent_func_name": "leave_group",
    "description": "delete the leave message",
    "aliases": [
      "removeleave",
      "delleave"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet leave message-remove"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave message-remove"
  },
  "greet_leave_message-preview": {
    "raw_name": "message-preview",
    "func_name": "leave_message_preview",
    "parent_func_name": "leave_group",
    "description": "see how your leave message looks",
    "aliases": [
      "previewleave"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet leave message-preview"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave message-preview"
  },
  "greet_leave_channel-add": {
    "raw_name": "channel-add",
    "func_name": "leave_channel_add",
    "parent_func_name": "leave_group",
    "description": "add a leave message channel",
    "aliases": [
      "addleavechannel"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet leave channel-add <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave channel-add"
  },
  "greet_leave_channel-remove": {
    "raw_name": "channel-remove",
    "func_name": "leave_channel_remove",
    "parent_func_name": "leave_group",
    "description": "remove a leave message channel",
    "aliases": [
      "removeleavechannel"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet leave channel-remove <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet leave channel-remove"
  },
  "greet_autorole": {
    "raw_name": "autorole",
    "func_name": "autorole_group",
    "parent_func_name": "greet_prefix",
    "description": "give roles to new members",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet autorole"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet autorole bots",
      "greet autorole clear",
      "greet autorole humans",
      "greet autorole list",
      "greet autorole remove"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole"
  },
  "greet_autorole_bots": {
    "raw_name": "bots",
    "func_name": "autorole_bots",
    "parent_func_name": "autorole_group",
    "description": "give bots a role when they join",
    "aliases": [
      "botautorole",
      "botrole"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet autorole bots <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole bots"
  },
  "greet_autorole_humans": {
    "raw_name": "humans",
    "func_name": "autorole_humans",
    "parent_func_name": "autorole_group",
    "description": "give humans a role when they join",
    "aliases": [
      "humanautorole",
      "humanrole"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet autorole humans <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole humans"
  },
  "greet_autorole_remove": {
    "raw_name": "remove",
    "func_name": "autorole_remove",
    "parent_func_name": "autorole_group",
    "description": "remove an autorole",
    "aliases": [
      "removeautorole",
      "delautorole"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!greet autorole remove <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole remove"
  },
  "greet_autorole_list": {
    "raw_name": "list",
    "func_name": "autorole_list",
    "parent_func_name": "autorole_group",
    "description": "show all autoroles",
    "aliases": [
      "listautoroles"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet autorole list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole list"
  },
  "greet_autorole_clear": {
    "raw_name": "clear",
    "func_name": "autorole_clear",
    "parent_func_name": "autorole_group",
    "description": "remove all autoroles",
    "aliases": [
      "clearautoroles"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet autorole clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet autorole clear"
  },
  "greet_variables": {
    "raw_name": "variables",
    "func_name": "greet_variables",
    "parent_func_name": "greet_prefix",
    "description": "see all available placeholders",
    "aliases": [
      "vars",
      "placeholders"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet variables"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet variables"
  },
  "greet_test": {
    "raw_name": "test",
    "func_name": "test_group",
    "parent_func_name": "greet_prefix",
    "description": "test your messages",
    "aliases": [],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet test"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "greet test leave",
      "greet test welcome"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet test"
  },
  "greet_test_welcome": {
    "raw_name": "welcome",
    "func_name": "test_welcome",
    "parent_func_name": "test_group",
    "description": "send a test welcome message",
    "aliases": [
      "greet",
      "join"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet test welcome"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet test welcome"
  },
  "greet_test_leave": {
    "raw_name": "leave",
    "func_name": "test_leave",
    "parent_func_name": "test_group",
    "description": "send a test leave message",
    "aliases": [
      "goodbye"
    ],
    "category": "automation",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!greet test leave"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\automation\\welcome.py",
    "name": "greet test leave"
  }
};