// AUTO-GENERATED: Commands commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  raw_name?: string;
  func_name?: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const COMMANDS_COMMANDS: Record<string, Command> = {
  "commands": {
    "raw_name": "commands",
    "func_name": "commands_group",
    "parent_func_name": null,
    "description": "Manage command restrictions and permissions",
    "aliases": [
      "cmd",
      "command"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "commands disable",
      "commands disabled",
      "commands enable",
      "commands help",
      "commands restrict",
      "commands unrestrict"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands"
  },
  "commands_unrestrict": {
    "raw_name": "unrestrict",
    "func_name": "unrestrict_group",
    "parent_func_name": "commands_group",
    "description": "Remove restrictions from commands",
    "aliases": [
      "unlimit",
      "unblock"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands unrestrict"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "commands unrestrict permission",
      "commands unrestrict role"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands unrestrict"
  },
  "commands_unrestrict_permission": {
    "raw_name": "permission",
    "func_name": "unrestrict_permission",
    "parent_func_name": "unrestrict_group",
    "description": "Remove a permission restriction from a command",
    "aliases": [
      "perm"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      },
      {
        "name": "permission",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands unrestrict permission <command> <permission>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands unrestrict permission"
  },
  "commands_unrestrict_role": {
    "raw_name": "role",
    "func_name": "unrestrict_role",
    "parent_func_name": "unrestrict_group",
    "description": "Remove a role restriction from a command",
    "aliases": [
      "roles"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      },
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands unrestrict role <command> <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands unrestrict role"
  },
  "commands_restrict": {
    "raw_name": "restrict",
    "func_name": "restrict_group",
    "parent_func_name": "commands_group",
    "description": "Restrict commands to roles or permissions",
    "aliases": [
      "res"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands restrict"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "commands restrict permission",
      "commands restrict role"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands restrict"
  },
  "commands_restrict_permission": {
    "raw_name": "permission",
    "func_name": "restrict_permission",
    "parent_func_name": "restrict_group",
    "description": "Require a Discord permission to use a command",
    "aliases": [
      "perm"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      },
      {
        "name": "permission",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands restrict permission <command> <permission>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands restrict permission"
  },
  "commands_restrict_role": {
    "raw_name": "role",
    "func_name": "restrict_role",
    "parent_func_name": "restrict_group",
    "description": "Block a role from using a command",
    "aliases": [
      "roles"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      },
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands restrict role <command> <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands restrict role"
  },
  "commands_disable": {
    "raw_name": "disable",
    "func_name": "disable_group",
    "parent_func_name": "commands_group",
    "description": "Disable commands in channels or server-wide",
    "aliases": [
      "dis"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands disable"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "commands disable channel",
      "commands disable server"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands disable"
  },
  "commands_disable_channel": {
    "raw_name": "channel",
    "func_name": "disable_channel",
    "parent_func_name": "disable_group",
    "description": "Disable a command in the current channel",
    "aliases": [
      "chan",
      "c"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands disable channel <command>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands disable channel"
  },
  "commands_disable_server": {
    "raw_name": "server",
    "func_name": "disable_server",
    "parent_func_name": "disable_group",
    "description": "Disable a command server-wide",
    "aliases": [
      "guild",
      "s"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands disable server <command>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands disable server"
  },
  "commands_enable": {
    "raw_name": "enable",
    "func_name": "enable_command",
    "parent_func_name": "commands_group",
    "description": "Re-enable a disabled command",
    "aliases": [
      "en"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "command",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!commands enable <command>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands enable"
  },
  "commands_disabled": {
    "raw_name": "disabled",
    "func_name": "commands_disabled",
    "parent_func_name": "commands_group",
    "description": "List disabled commands",
    "aliases": [
      "disabledlist",
      "listdisabled"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands disabled"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands disabled"
  },
  "commands_help": {
    "raw_name": "help",
    "func_name": "commands_help",
    "parent_func_name": "commands_group",
    "description": "Show help for command management",
    "aliases": [
      "h",
      "?"
    ],
    "category": "commands",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!commands help"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\commands\\commands.py",
    "name": "commands help"
  }
};