// AUTO-GENERATED: Fun commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const FUN_COMMANDS: Record<string, Command> = {
  "fun": {
    "raw_name": "fun",
    "func_name": "fun_group",
    "parent_func_name": null,
    "description": "play games like magic 8ball, dice, and coin flip",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!fun"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "fun 8ball",
      "fun base64",
      "fun caption",
      "fun choose",
      "fun coinflip",
      "fun dice",
      "fun dih",
      "fun enlarge",
      "fun humble",
      "fun image",
      "fun img2gif",
      "fun rps",
      "fun sha256",
      "fun steal",
      "fun translate",
      "fun urban"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun"
  },
  "fun_enlarge": {
    "raw_name": "enlarge",
    "func_name": "fun_enlarge",
    "parent_func_name": "fun_group",
    "description": "enlarge an emoji",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "emoji",
        "type": "str"
      }
    ],
    "examples": [
      "!fun enlarge [emoji]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun enlarge"
  },
  "fun_8ball": {
    "raw_name": "8ball",
    "func_name": "fun_8ball",
    "parent_func_name": "fun_group",
    "description": "ask the magic 8ball a question",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "question",
        "type": "str"
      }
    ],
    "examples": [
      "!fun 8ball [question]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun 8ball"
  },
  "fun_dice": {
    "raw_name": "dice",
    "func_name": "fun_dice",
    "parent_func_name": "fun_group",
    "description": "roll some dice",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "sides",
        "type": "int"
      },
      {
        "name": "count",
        "type": "int"
      }
    ],
    "examples": [
      "!fun dice [sides] [count]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun dice"
  },
  "fun_coinflip": {
    "raw_name": "coinflip",
    "func_name": "fun_coinflip",
    "parent_func_name": "fun_group",
    "description": "flip a virtual coin to get heads or tails",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!fun coinflip"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun coinflip"
  },
  "fun_dih": {
    "raw_name": "dih",
    "func_name": "fun_pp",
    "parent_func_name": "fun_group",
    "description": "check dih size",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!fun dih [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun dih"
  },
  "fun_choose": {
    "raw_name": "choose",
    "func_name": "fun_choose",
    "parent_func_name": "fun_group",
    "description": "let me choose from your options",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [
      {
        "name": "options",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!fun choose <options>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun choose"
  },
  "fun_rps": {
    "raw_name": "rps",
    "func_name": "fun_rps",
    "parent_func_name": "fun_group",
    "description": "play rock paper scissors with the bot",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [
      {
        "name": "choice",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!fun rps <choice>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun rps"
  },
  "fun_humble": {
    "raw_name": "humble",
    "func_name": "fun_humble",
    "parent_func_name": "fun_group",
    "description": "generate AI-powered packgod style roasts",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!fun humble [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun humble"
  },
  "fun_caption": {
    "raw_name": "caption",
    "func_name": "fun_caption",
    "parent_func_name": "fun_group",
    "description": "add caption text to images",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "attachment",
        "type": "Attachment"
      }
    ],
    "examples": [
      "!fun caption <text> [attachment]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun caption"
  },
  "fun_base64": {
    "raw_name": "base64",
    "func_name": "fun_base64",
    "parent_func_name": "fun_group",
    "description": "encode or decode base64 text",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [
      {
        "name": "action",
        "type": "str"
      },
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!fun base64 <action> <text>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun base64"
  },
  "fun_sha256": {
    "raw_name": "sha256",
    "func_name": "fun_sha256",
    "parent_func_name": "fun_group",
    "description": "generate SHA256 hash of text",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "text",
        "type": "str"
      }
    ],
    "examples": [
      "!fun sha256 [text]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun sha256"
  },
  "fun_steal": {
    "raw_name": "steal",
    "func_name": "fun_steal",
    "parent_func_name": "fun_group",
    "description": "steal emojis and stickers from messages",
    "aliases": [],
    "category": "fun",
    "permissions": [
      "Manage Expressions"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_id",
        "type": "str"
      },
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!fun steal [message_id] [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun steal"
  },
  "fun_translate": {
    "raw_name": "translate",
    "func_name": "fun_translate",
    "parent_func_name": "fun_group",
    "description": "translate text between languages",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "target_language",
        "type": "str"
      },
      {
        "name": "text",
        "type": "str"
      }
    ],
    "examples": [
      "!fun translate [target_language] [text]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun translate"
  },
  "pp": {
    "raw_name": "pp",
    "func_name": "pp",
    "parent_func_name": null,
    "description": "check pp size",
    "aliases": [
      "dih"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!pp [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "pp"
  },
  "dihr": {
    "raw_name": "dihr",
    "func_name": "dihr",
    "parent_func_name": null,
    "description": "fixed 67 inch result",
    "aliases": [
      "ppr"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!dihr [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "dihr"
  },
  "fun_urban": {
    "raw_name": "urban",
    "func_name": "fun_urban",
    "parent_func_name": "fun_group",
    "description": "look up a term on Urban Dictionary",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "term",
        "type": "str"
      }
    ],
    "examples": [
      "!fun urban [term]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun urban"
  },
  "fun_image": {
    "raw_name": "image",
    "func_name": "fun_image",
    "parent_func_name": "fun_group",
    "description": "scrape the web for images",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!fun image [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun image"
  },
  "fun_img2gif": {
    "raw_name": "img2gif",
    "func_name": "fun_img2gif",
    "parent_func_name": "fun_group",
    "description": "turn an image into a gif",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "file",
        "type": "Attachment"
      }
    ],
    "examples": [
      "!fun img2gif [file]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\fun.py",
    "name": "fun img2gif"
  },
  "gpt": {
    "raw_name": "gpt",
    "func_name": "gpt",
    "parent_func_name": null,
    "description": "AI commands",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt [query]"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "gpt ask",
      "gpt channel",
      "gpt disable",
      "gpt edit",
      "gpt frequency",
      "gpt generate",
      "gpt personality",
      "gpt tts"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt"
  },
  "gpt_channel": {
    "raw_name": "channel",
    "func_name": "channel",
    "parent_func_name": "gpt",
    "description": "Set up a channel for automated AI responses",
    "aliases": [],
    "category": "fun",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!gpt channel [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt channel"
  },
  "gpt_disable": {
    "raw_name": "disable",
    "func_name": "disable",
    "parent_func_name": "gpt",
    "description": "Disable automated AI responses in this channel",
    "aliases": [],
    "category": "fun",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!gpt disable [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt disable"
  },
  "gpt_frequency": {
    "raw_name": "frequency",
    "func_name": "frequency",
    "parent_func_name": "gpt",
    "description": "Set how often AI should respond automatically",
    "aliases": [
      "freq"
    ],
    "category": "fun",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt frequency [duration]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt frequency"
  },
  "gpt_personality": {
    "raw_name": "personality",
    "func_name": "personality",
    "parent_func_name": "gpt",
    "description": "Set a custom AI personality",
    "aliases": [
      "persona"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "personality",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt personality [personality]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt personality"
  },
  "gpt_ask": {
    "raw_name": "ask",
    "func_name": "ask",
    "parent_func_name": "gpt",
    "description": "Ask the AI a question",
    "aliases": [
      "chat",
      "query",
      "question"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt ask [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt ask"
  },
  "gpt_generate": {
    "raw_name": "generate",
    "func_name": "generate_image",
    "parent_func_name": "gpt",
    "description": "No description provided",
    "aliases": [
      "gen",
      "clanker",
      "draw"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt generate [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt generate"
  },
  "gpt_edit": {
    "raw_name": "edit",
    "func_name": "gpt_edit",
    "parent_func_name": "gpt",
    "description": "Edit an image using AI",
    "aliases": [],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt edit [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt edit"
  },
  "gpt_tts": {
    "raw_name": "tts",
    "func_name": "tts",
    "parent_func_name": "gpt",
    "description": "No description provided",
    "aliases": [
      "say",
      "speak"
    ],
    "category": "fun",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "prompt",
        "type": "str"
      }
    ],
    "examples": [
      "!gpt tts [prompt]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\fun\\gpt.py",
    "name": "gpt tts"
  }
};
