// AUTO-GENERATED: Import all command categories
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

import { AUTOMATION_COMMANDS } from "./automation-commands";
import { COMMANDS_COMMANDS } from "./commands-commands";
import { CUSTOMIZATION_COMMANDS } from "./customization-commands";
import { ENGAGEMENT_COMMANDS } from "./engagement-commands";
import { FUN_COMMANDS } from "./fun-commands";
import { MODERATION_COMMANDS } from "./moderation-commands";
import { MUSIC_COMMANDS } from "./music-commands";
import { ROLEPLAY_COMMANDS } from "./roleplay-commands";
import { SECURITY_COMMANDS } from "./security-commands";
import { SERVER_COMMANDS } from "./server-commands";
import { SOCIAL_COMMANDS } from "./social-commands";
import { UTILITY_COMMANDS } from "./utility-commands";

export const ALL_COMMANDS: Record<string, Command> = {
  ...AUTOMATION_COMMANDS,
  ...COMMANDS_COMMANDS,
  ...CUSTOMIZATION_COMMANDS,
  ...ENGAGEMENT_COMMANDS,
  ...FUN_COMMANDS,
  ...MODERATION_COMMANDS,
  ...MUSIC_COMMANDS,
  ...ROLEPLAY_COMMANDS,
  ...SECURITY_COMMANDS,
  ...SERVER_COMMANDS,
  ...SOCIAL_COMMANDS,
  ...UTILITY_COMMANDS,
};
