// AUTO-GENERATED: Moderation commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const MODERATION_COMMANDS: Record<string, Command> = {
  "kick": {
    "raw_name": "kick",
    "func_name": "kick_command",
    "parent_func_name": "moderation_user",
    "description": "kick a member from the server",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!kick <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "kick"
  },
  "hardban": {
    "raw_name": "hardban",
    "func_name": "hardban_command",
    "parent_func_name": "moderation_user",
    "description": "permanently ban a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!hardban <target> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "hardban"
  },
  "softban": {
    "raw_name": "softban",
    "func_name": "softban_command",
    "parent_func_name": "moderation_user",
    "description": "ban and immediately unban a member (clears messages)",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!softban <target> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "softban"
  },
  "ban": {
    "raw_name": "ban",
    "func_name": "ban_command",
    "parent_func_name": "moderation_user",
    "description": "ban a member or user ID",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "target",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!ban <target> [duration] [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "ban"
  },
  "unbanall": {
    "raw_name": "unbanall",
    "func_name": "unbanall_command",
    "parent_func_name": "moderation_bulk",
    "description": "unban all banned users",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!unbanall"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unbanall"
  },
  "unban": {
    "raw_name": "unban",
    "func_name": "unban_command",
    "parent_func_name": "moderation_user",
    "description": "unban a user",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "user_id",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!unban <user_id> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unban"
  },
  "removehardban": {
    "raw_name": "removehardban",
    "func_name": "removehardban_command",
    "parent_func_name": "moderation_user",
    "description": "remove hardban status from a user",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "user_id",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!removehardban <user_id> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "removehardban"
  },
  "channels": {
    "raw_name": "channels",
    "func_name": "channels",
    "parent_func_name": null,
    "description": "channel tools",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!channels"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "channels category",
      "channels clone",
      "channels create",
      "channels delete",
      "channels list",
      "channels protect",
      "channels unprotect"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels"
  },
  "channels_create": {
    "raw_name": "create",
    "func_name": "channels_create",
    "parent_func_name": "channels",
    "description": "make new text/voice channels or categories",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!channels create"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "channels create category",
      "channels create text",
      "channels create voice"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels create"
  },
  "channels_create_text": {
    "raw_name": "text",
    "func_name": "create_text_channel",
    "parent_func_name": "channels_create",
    "description": "make a new text channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "category",
        "type": "CategoryChannel"
      }
    ],
    "examples": [
      "!channels create text <name> [category]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels create text"
  },
  "channels_create_voice": {
    "raw_name": "voice",
    "func_name": "create_voice_channel",
    "parent_func_name": "channels_create",
    "description": "make a new voice channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "category",
        "type": "CategoryChannel"
      }
    ],
    "examples": [
      "!channels create voice <name> [category]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels create voice"
  },
  "channels_create_category": {
    "raw_name": "category",
    "func_name": "create_category",
    "parent_func_name": "channels_create",
    "description": "make a new category",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!channels create category <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels create category"
  },
  "channels_delete": {
    "raw_name": "delete",
    "func_name": "channels_delete",
    "parent_func_name": "channels",
    "description": "delete a channel or category",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "GuildChannel"
      }
    ],
    "examples": [
      "!channels delete [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels delete"
  },
  "channels_clone": {
    "raw_name": "clone",
    "func_name": "channels_clone",
    "parent_func_name": "channels",
    "description": "copy a channel or category",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "GuildChannel"
      }
    ],
    "examples": [
      "!channels clone [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels clone"
  },
  "channels_protect": {
    "raw_name": "protect",
    "func_name": "channels_protect",
    "parent_func_name": "channels",
    "description": "protect channels from nuke and snipe",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!channels protect"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "channels protect nuke",
      "channels protect snipe"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels protect"
  },
  "channels_protect_nuke": {
    "raw_name": "nuke",
    "func_name": "protect_nuke",
    "parent_func_name": "channels_protect",
    "description": "protect a channel from being nuked",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!channels protect nuke [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels protect nuke"
  },
  "channels_protect_snipe": {
    "raw_name": "snipe",
    "func_name": "protect_snipe",
    "parent_func_name": "channels_protect",
    "description": "protect a channel from snipe",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!channels protect snipe [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels protect snipe"
  },
  "channels_unprotect": {
    "raw_name": "unprotect",
    "func_name": "channels_unprotect",
    "parent_func_name": "channels",
    "description": "remove protection from channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!channels unprotect"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "channels unprotect nuke",
      "channels unprotect snipe"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels unprotect"
  },
  "channels_unprotect_nuke": {
    "raw_name": "nuke",
    "func_name": "unprotect_nuke",
    "parent_func_name": "channels_unprotect",
    "description": "let a channel be nuked again",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!channels unprotect nuke [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels unprotect nuke"
  },
  "channels_unprotect_snipe": {
    "raw_name": "snipe",
    "func_name": "unprotect_snipe",
    "parent_func_name": "channels_unprotect",
    "description": "let snipe work in a channel again",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!channels unprotect snipe [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels unprotect snipe"
  },
  "channels_list": {
    "raw_name": "list",
    "func_name": "list_protected",
    "parent_func_name": "channels",
    "description": "see which channels are protected",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "protection_type",
        "type": "str"
      }
    ],
    "examples": [
      "!channels list [protection_type]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels list"
  },
  "channels_category": {
    "raw_name": "category",
    "func_name": "channels_category",
    "parent_func_name": "channels",
    "description": "category tools",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!channels category"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "channels category clone",
      "channels category create",
      "channels category delete"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels category"
  },
  "channels_category_create": {
    "raw_name": "create",
    "func_name": "channels_category_create",
    "parent_func_name": "channels_category",
    "description": "make a new category",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!channels category create <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels category create"
  },
  "channels_category_delete": {
    "raw_name": "delete",
    "func_name": "channels_category_delete",
    "parent_func_name": "channels_category",
    "description": "delete a category (must be empty)",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "category",
        "type": "CategoryChannel"
      }
    ],
    "examples": [
      "!channels category delete [category]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels category delete"
  },
  "channels_category_clone": {
    "raw_name": "clone",
    "func_name": "channels_category_clone",
    "parent_func_name": "channels_category",
    "description": "copy a category with all its channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Channels"
    ],
    "required_args": [
      {
        "name": "category",
        "type": "CategoryChannel"
      }
    ],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!channels category clone <category> [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\channels.py",
    "name": "channels category clone"
  },
  "nuke": {
    "raw_name": "nuke",
    "func_name": "nuke_command",
    "parent_func_name": "moderation_channel",
    "description": "delete and recreate channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!nuke [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "nuke"
  },
  "purge": {
    "raw_name": "purge",
    "func_name": "purge",
    "parent_func_name": null,
    "description": "delete lots of messages quickly",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge [amount]"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "purge all",
      "purge bot",
      "purge cleanup",
      "purge contains",
      "purge embeds",
      "purge emoji",
      "purge files",
      "purge humans",
      "purge images",
      "purge invites",
      "purge length",
      "purge links",
      "purge mentions",
      "purge reactions",
      "purge user"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge"
  },
  "purge_all": {
    "raw_name": "all",
    "func_name": "purge_all",
    "parent_func_name": "purge",
    "description": "delete any type of message",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!purge all <amount>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge all"
  },
  "purge_user": {
    "raw_name": "user",
    "func_name": "purge_user",
    "parent_func_name": "purge",
    "description": "delete messages from a specific person",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge user <user> [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge user"
  },
  "purge_bot": {
    "raw_name": "bot",
    "func_name": "purge_bot",
    "parent_func_name": "purge",
    "description": "delete bot messages",
    "aliases": [
      "bots"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge bot [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge bot"
  },
  "purge_humans": {
    "raw_name": "humans",
    "func_name": "purge_humans",
    "parent_func_name": "purge",
    "description": "delete messages from humans only",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge humans [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge humans"
  },
  "purge_contains": {
    "raw_name": "contains",
    "func_name": "purge_contains",
    "parent_func_name": "purge",
    "description": "delete messages with certain text",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [
      {
        "name": "text",
        "type": "str"
      },
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!purge contains <text> <amount>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge contains"
  },
  "purge_links": {
    "raw_name": "links",
    "func_name": "purge_links",
    "parent_func_name": "purge",
    "description": "delete messages with links",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge links [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge links"
  },
  "purge_embeds": {
    "raw_name": "embeds",
    "func_name": "purge_embeds",
    "parent_func_name": "purge",
    "description": "delete messages with embeds",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge embeds [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge embeds"
  },
  "purge_emoji": {
    "raw_name": "emoji",
    "func_name": "purge_emoji",
    "parent_func_name": "purge",
    "description": "delete messages with emojis",
    "aliases": [
      "emojis"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge emoji [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge emoji"
  },
  "purge_images": {
    "raw_name": "images",
    "func_name": "purge_images",
    "parent_func_name": "purge",
    "description": "delete messages with images",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge images [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge images"
  },
  "purge_files": {
    "raw_name": "files",
    "func_name": "purge_files",
    "parent_func_name": "purge",
    "description": "delete messages with files",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge files [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge files"
  },
  "purge_mentions": {
    "raw_name": "mentions",
    "func_name": "purge_mentions",
    "parent_func_name": "purge",
    "description": "delete messages with mentions",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge mentions [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge mentions"
  },
  "purge_reactions": {
    "raw_name": "reactions",
    "func_name": "purge_reactions",
    "parent_func_name": "purge",
    "description": "delete messages with reactions",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge reactions [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge reactions"
  },
  "purge_cleanup": {
    "raw_name": "cleanup",
    "func_name": "purge_cleanup",
    "parent_func_name": "purge",
    "description": "clean up bot commands and responses",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge cleanup [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge cleanup"
  },
  "purge_invites": {
    "raw_name": "invites",
    "func_name": "purge_invites",
    "parent_func_name": "purge",
    "description": "delete discord invite links",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "examples": [
      "!purge invites [amount]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge invites"
  },
  "purge_length": {
    "raw_name": "length",
    "func_name": "purge_length",
    "parent_func_name": "purge",
    "description": "delete messages by length",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [
      {
        "name": "amount",
        "type": "int"
      }
    ],
    "optional_args": [
      {
        "name": "min_length",
        "type": "int"
      },
      {
        "name": "max_length",
        "type": "int"
      }
    ],
    "examples": [
      "!purge length <amount> [min_length] [max_length]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\clear.py",
    "name": "purge length"
  },
  "clear": {
    "raw_name": "clear",
    "func_name": "snipe_clear_command",
    "parent_func_name": "moderation_snipe",
    "description": "clear sniped messages",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "clear"
  },
  "nickname": {
    "raw_name": "nickname",
    "func_name": "nick_prefix",
    "parent_func_name": null,
    "description": "change a user's nickname",
    "aliases": [
      "nick",
      "setnick"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Nicknames"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "member",
        "type": "Member"
      },
      {
        "name": "nickname",
        "type": "str"
      }
    ],
    "examples": [
      "!nickname [member] [nickname]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\forcenick.py",
    "name": "nickname"
  },
  "forcenick": {
    "raw_name": "forcenick",
    "func_name": "forcenick_command",
    "parent_func_name": "moderation_user",
    "description": "force a nickname on a user",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "nickname",
        "type": "str"
      }
    ],
    "examples": [
      "!forcenick <member> [nickname]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "forcenick"
  },
  "removeforcenick": {
    "raw_name": "removeforcenick",
    "func_name": "removeforcenick_command",
    "parent_func_name": "moderation_user",
    "description": "remove forced nickname from a user",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [],
    "examples": [
      "!removeforcenick <member>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "removeforcenick"
  },
  "ghostping": {
    "raw_name": "ghostping",
    "func_name": "ghostping",
    "parent_func_name": null,
    "description": "catch people who ghost ping",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!ghostping"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "ghostping add",
      "ghostping list",
      "ghostping remove"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\ghostping.py",
    "name": "ghostping"
  },
  "ghostping_add": {
    "raw_name": "add",
    "func_name": "ghostping_add",
    "parent_func_name": "ghostping",
    "description": "set up a channel to ghost ping new members",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [
      {
        "name": "delay",
        "type": "int"
      }
    ],
    "examples": [
      "!ghostping add <channel> [delay]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\ghostping.py",
    "name": "ghostping add"
  },
  "ghostping_remove": {
    "raw_name": "remove",
    "func_name": "ghostping_remove",
    "parent_func_name": "ghostping",
    "description": "stop ghost pinging in a channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!ghostping remove <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\ghostping.py",
    "name": "ghostping remove"
  },
  "ghostping_list": {
    "raw_name": "list",
    "func_name": "ghostping_list",
    "parent_func_name": "ghostping",
    "description": "see all ghost ping channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!ghostping list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\ghostping.py",
    "name": "ghostping list"
  },
  "lock": {
    "raw_name": "lock",
    "func_name": "lock_command",
    "parent_func_name": "moderation_channel",
    "description": "lock a channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      },
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "examples": [
      "!lock [channel] [role]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "lock"
  },
  "unlock": {
    "raw_name": "unlock",
    "func_name": "unlock_command",
    "parent_func_name": "moderation_channel",
    "description": "unlock a channel",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      },
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "examples": [
      "!unlock [channel] [role]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unlock"
  },
  "lockall": {
    "raw_name": "lockall",
    "func_name": "lockall_command",
    "parent_func_name": "moderation_channel",
    "description": "lock all channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "examples": [
      "!lockall [role]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "lockall"
  },
  "unlockall": {
    "raw_name": "unlockall",
    "func_name": "unlockall_command",
    "parent_func_name": "moderation_channel",
    "description": "unlock all channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "examples": [
      "!unlockall [role]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unlockall"
  },
  "slowmode": {
    "raw_name": "slowmode",
    "func_name": "slowmode_command",
    "parent_func_name": "moderation_channel",
    "description": "set channel slowmode",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "delay",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!slowmode <delay>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "slowmode"
  },
  "snipe": {
    "raw_name": "snipe",
    "func_name": "snipe_prefix",
    "parent_func_name": null,
    "description": "No description provided",
    "aliases": [
      "s"
    ],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "index",
        "type": "int"
      }
    ],
    "examples": [
      "!snipe [index]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\snipe.py",
    "name": "snipe"
  },
  "editsnipe": {
    "raw_name": "editsnipe",
    "func_name": "editsnipe_prefix",
    "parent_func_name": null,
    "description": "No description provided",
    "aliases": [
      "es"
    ],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "index",
        "type": "int"
      }
    ],
    "examples": [
      "!editsnipe [index]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\snipe.py",
    "name": "editsnipe"
  },
  "reactionsnipe": {
    "raw_name": "reactionsnipe",
    "func_name": "reactionsnipe_prefix",
    "parent_func_name": null,
    "description": "see recently removed reactions",
    "aliases": [
      "rsnipe",
      "rs"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "limit",
        "type": "int"
      }
    ],
    "examples": [
      "!reactionsnipe [limit]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\snipe.py",
    "name": "reactionsnipe"
  },
  "clearsnipe": {
    "raw_name": "clearsnipe",
    "func_name": "clearsnipe_prefix",
    "parent_func_name": null,
    "description": "clear saved snipe data",
    "aliases": [
      "cs"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!clearsnipe"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\snipe.py",
    "name": "clearsnipe"
  },
  "sticky": {
    "raw_name": "sticky",
    "func_name": "sticky",
    "parent_func_name": null,
    "description": "create sticky messages that stay at the bottom of channels",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!sticky"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "sticky edit",
      "sticky list",
      "sticky remove",
      "sticky set"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\sticky.py",
    "name": "sticky"
  },
  "sticky_set": {
    "raw_name": "set",
    "func_name": "sticky_set",
    "parent_func_name": "sticky",
    "description": "set a sticky message for a channel",
    "aliases": [
      "add",
      "create"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!sticky set [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\sticky.py",
    "name": "sticky set"
  },
  "sticky_list": {
    "raw_name": "list",
    "func_name": "sticky_list",
    "parent_func_name": "sticky",
    "description": "see all sticky messages",
    "aliases": [
      "ls",
      "show"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!sticky list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\sticky.py",
    "name": "sticky list"
  },
  "sticky_remove": {
    "raw_name": "remove",
    "func_name": "remove_sticky",
    "parent_func_name": "sticky",
    "description": "remove a sticky message from a channel",
    "aliases": [
      "rm",
      "del",
      "delete"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!sticky remove [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\sticky.py",
    "name": "sticky remove"
  },
  "sticky_edit": {
    "raw_name": "edit",
    "func_name": "sticky_edit",
    "parent_func_name": "sticky",
    "description": "edit an existing sticky message",
    "aliases": [
      "modify",
      "update"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "examples": [
      "!sticky edit [message]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\sticky.py",
    "name": "sticky edit"
  },
  "mute": {
    "raw_name": "mute",
    "func_name": "mute_command",
    "parent_func_name": "moderation_user",
    "description": "mute a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!mute <member> [duration] [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "mute"
  },
  "unmute": {
    "raw_name": "unmute",
    "func_name": "unmute_command",
    "parent_func_name": "moderation_user",
    "description": "unmute a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!unmute <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unmute"
  },
  "reactionmute": {
    "raw_name": "reactionmute",
    "func_name": "reactionmute_command",
    "parent_func_name": "moderation_user",
    "description": "prevent someone from reacting for a while",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!reactionmute <member> [duration] [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "reactionmute"
  },
  "unreactionmute": {
    "raw_name": "unreactionmute",
    "func_name": "unreactionmute_command",
    "parent_func_name": "moderation_user",
    "description": "unreactionmute a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!unreactionmute <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unreactionmute"
  },
  "imagemute": {
    "raw_name": "imagemute",
    "func_name": "imagemute_command",
    "parent_func_name": "moderation_user",
    "description": "prevent someone from sending images/embeds for a while",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!imagemute <member> [duration] [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "imagemute"
  },
  "unimagemute": {
    "raw_name": "unimagemute",
    "func_name": "unimagemute_command",
    "parent_func_name": "moderation_user",
    "description": "unimagemute a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!unimagemute <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unimagemute"
  },
  "timeout": {
    "raw_name": "timeout",
    "func_name": "timeout_command",
    "parent_func_name": "moderation_user",
    "description": "timeout a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!timeout <member> [duration] [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "timeout"
  },
  "untimeout": {
    "raw_name": "untimeout",
    "func_name": "untimeout_command",
    "parent_func_name": "moderation_user",
    "description": "remove timeout from a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!untimeout <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "untimeout"
  },
  "untimeoutall": {
    "raw_name": "untimeoutall",
    "func_name": "untimeoutall_command",
    "parent_func_name": "moderation_bulk",
    "description": "remove timeout from all timed out members",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!untimeoutall"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "untimeoutall"
  },
  "unmuteall": {
    "raw_name": "unmuteall",
    "func_name": "unmuteall_command",
    "parent_func_name": "moderation_bulk",
    "description": "unmute all muted members",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!unmuteall"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "unmuteall"
  },
  "warn": {
    "raw_name": "warn",
    "func_name": "warn_command",
    "parent_func_name": "moderation_user",
    "description": "warn a member",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [
      {
        "name": "reason",
        "type": "str"
      }
    ],
    "examples": [
      "!warn <member> [reason]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "warn"
  },
  "modwarnings": {
    "raw_name": "modwarnings",
    "func_name": "moderation_warnings",
    "parent_func_name": null,
    "description": "see someone's warnings",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [
      {
        "name": "member",
        "type": "Member"
      }
    ],
    "optional_args": [],
    "examples": [
      "!modwarnings <member>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\warn.py",
    "name": "modwarnings"
  },
  "warnings": {
    "raw_name": "warnings",
    "func_name": "warnings_prefix",
    "parent_func_name": null,
    "description": "see warnings for a user",
    "aliases": [
      "warns",
      "w-list",
      "w-show"
    ],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "text"
      }
    ],
    "examples": [
      "!warnings [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\warn.py",
    "name": "warnings"
  },
  "modthresholds": {
    "raw_name": "modthresholds",
    "func_name": "moderation_thresholds",
    "parent_func_name": null,
    "description": "see warning thresholds",
    "aliases": [],
    "category": "moderation",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!modthresholds"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\warn.py",
    "name": "modthresholds"
  },
  "thresholds": {
    "raw_name": "thresholds",
    "func_name": "thresholds_command",
    "parent_func_name": "moderation_warnings",
    "description": "view warning thresholds",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!thresholds"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "thresholds"
  },
  "setwarnthreshold": {
    "raw_name": "setwarnthreshold",
    "func_name": "setwarnthreshold_prefix",
    "parent_func_name": null,
    "description": "set warning thresholds",
    "aliases": [
      "setthreshold",
      "modsetthreshold"
    ],
    "category": "moderation",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "threshold_type",
        "type": "str"
      },
      {
        "name": "value",
        "type": "str"
      }
    ],
    "examples": [
      "!setwarnthreshold [threshold_type] [value]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\warn.py",
    "name": "setwarnthreshold"
  },
  "view": {
    "raw_name": "view",
    "func_name": "warnings_view_command",
    "parent_func_name": "moderation_warnings",
    "description": "view warnings for a user",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "user",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!view <user>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "view"
  },
  "setthreshold": {
    "raw_name": "setthreshold",
    "func_name": "setthreshold_command",
    "parent_func_name": "moderation_warnings",
    "description": "set warning thresholds",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [
      {
        "name": "threshold_type",
        "type": "str"
      },
      {
        "name": "value",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!setthreshold <threshold_type> <value>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "setthreshold"
  },
  "deleted": {
    "raw_name": "deleted",
    "func_name": "snipe_deleted_command",
    "parent_func_name": "moderation_snipe",
    "description": "view deleted messages",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "index",
        "type": "int"
      }
    ],
    "examples": [
      "!deleted [index]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "deleted"
  },
  "edited": {
    "raw_name": "edited",
    "func_name": "snipe_edited_command",
    "parent_func_name": "moderation_snipe",
    "description": "view edited messages",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "index",
        "type": "int"
      }
    ],
    "examples": [
      "!edited [index]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "edited"
  },
  "reaction": {
    "raw_name": "reaction",
    "func_name": "snipe_reaction_command",
    "parent_func_name": "moderation_snipe",
    "description": "view removed reactions",
    "aliases": [],
    "category": "moderation",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "limit",
        "type": "int"
      }
    ],
    "examples": [
      "!reaction [limit]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\moderation\\__init__.py",
    "name": "reaction"
  }
};