// AUTO-GENERATED: Music commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const MUSIC_COMMANDS: Record<string, Command> = {
  "play": {
    "raw_name": "play",
    "func_name": "play_prefix",
    "parent_func_name": null,
    "description": "play a track",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!play [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "play"
  },
  "stop": {
    "raw_name": "stop",
    "func_name": "stop_prefix",
    "parent_func_name": null,
    "description": "stop and disconnect",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!stop"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "stop"
  },
  "pause": {
    "raw_name": "pause",
    "func_name": "pause_prefix",
    "parent_func_name": null,
    "description": "pause playback",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!pause"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "pause"
  },
  "resume": {
    "raw_name": "resume",
    "func_name": "resume_prefix",
    "parent_func_name": null,
    "description": "resume playback",
    "aliases": [
      "unpause"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!resume"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "resume"
  },
  "skip": {
    "raw_name": "skip",
    "func_name": "skip_prefix",
    "parent_func_name": null,
    "description": "skip the current track",
    "aliases": [
      "next"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!skip"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "skip"
  },
  "np": {
    "raw_name": "np",
    "func_name": "np_prefix",
    "parent_func_name": null,
    "description": "show now playing",
    "aliases": [
      "nowplaying"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!np"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "np"
  },
  "connect": {
    "raw_name": "connect",
    "func_name": "connect_prefix",
    "parent_func_name": null,
    "description": "join your voice channel",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!connect"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "connect"
  },
  "volume": {
    "raw_name": "volume",
    "func_name": "volume_prefix",
    "parent_func_name": null,
    "description": "set volume",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "volume",
        "type": "int"
      }
    ],
    "examples": [
      "!volume [volume]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "volume"
  },
  "repeat": {
    "raw_name": "repeat",
    "func_name": "repeat_prefix",
    "parent_func_name": null,
    "description": "set repeat mode",
    "aliases": [
      "loop"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "mode",
        "type": "str"
      }
    ],
    "examples": [
      "!repeat [mode]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "repeat"
  },
  "shuffle": {
    "raw_name": "shuffle",
    "func_name": "shuffle_prefix",
    "parent_func_name": null,
    "description": "shuffle the queue",
    "aliases": [
      "shuff"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!shuffle"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "shuffle"
  },
  "rewind": {
    "raw_name": "rewind",
    "func_name": "rewind_prefix",
    "parent_func_name": null,
    "description": "seek to a position in seconds",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "position",
        "type": "int"
      }
    ],
    "examples": [
      "!rewind [position]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\controls.py",
    "name": "rewind"
  },
  "music": {
    "raw_name": "music",
    "func_name": "music_group",
    "parent_func_name": null,
    "description": "music commands",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "music connect",
      "music np",
      "music pause",
      "music play",
      "music preset",
      "music queue",
      "music repeat",
      "music resume",
      "music rewind",
      "music shuffle",
      "music skip",
      "music stop",
      "music volume"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music"
  },
  "music_play": {
    "raw_name": "play",
    "func_name": "music_play",
    "parent_func_name": "music_group",
    "description": "play a song from a search query or url",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "examples": [
      "!music play [query]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music play"
  },
  "music_stop": {
    "raw_name": "stop",
    "func_name": "music_stop",
    "parent_func_name": "music_group",
    "description": "stop playback and disconnect",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music stop"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music stop"
  },
  "music_pause": {
    "raw_name": "pause",
    "func_name": "music_pause",
    "parent_func_name": "music_group",
    "description": "pause the current track",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music pause"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music pause"
  },
  "music_resume": {
    "raw_name": "resume",
    "func_name": "music_resume",
    "parent_func_name": "music_group",
    "description": "resume the current track",
    "aliases": [
      "unpause"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music resume"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music resume"
  },
  "music_skip": {
    "raw_name": "skip",
    "func_name": "music_skip",
    "parent_func_name": "music_group",
    "description": "skip the current track",
    "aliases": [
      "next"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music skip"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music skip"
  },
  "music_volume": {
    "raw_name": "volume",
    "func_name": "music_volume",
    "parent_func_name": "music_group",
    "description": "set the player volume",
    "aliases": [
      "vol"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "volume",
        "type": "int"
      }
    ],
    "examples": [
      "!music volume [volume]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music volume"
  },
  "music_repeat": {
    "raw_name": "repeat",
    "func_name": "music_repeat",
    "parent_func_name": "music_group",
    "description": "set repeat mode",
    "aliases": [
      "loop"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "mode",
        "type": "str"
      }
    ],
    "examples": [
      "!music repeat [mode]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music repeat"
  },
  "music_shuffle": {
    "raw_name": "shuffle",
    "func_name": "music_shuffle",
    "parent_func_name": "music_group",
    "description": "shuffle the queue",
    "aliases": [
      "shuff"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music shuffle"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music shuffle"
  },
  "music_rewind": {
    "raw_name": "rewind",
    "func_name": "music_rewind",
    "parent_func_name": "music_group",
    "description": "seek to a position in seconds",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "position",
        "type": "int"
      }
    ],
    "examples": [
      "!music rewind [position]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music rewind"
  },
  "music_np": {
    "raw_name": "np",
    "func_name": "music_np",
    "parent_func_name": "music_group",
    "description": "show the currently playing track",
    "aliases": [
      "nowplaying"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music np"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music np"
  },
  "music_connect": {
    "raw_name": "connect",
    "func_name": "music_connect",
    "parent_func_name": "music_group",
    "description": "connect to your voice channel",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music connect"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music connect"
  },
  "music_queue": {
    "raw_name": "queue",
    "func_name": "music_queue_group",
    "parent_func_name": "music_group",
    "description": "queue management",
    "aliases": [
      "q"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music queue"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "music queue empty",
      "music queue move",
      "music queue remove",
      "music queue shuffle",
      "music queue view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue"
  },
  "music_queue_view": {
    "raw_name": "view",
    "func_name": "music_queue_view",
    "parent_func_name": "music_queue_group",
    "description": "view the queue",
    "aliases": [
      "list"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music queue view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue view"
  },
  "music_queue_empty": {
    "raw_name": "empty",
    "func_name": "music_queue_empty",
    "parent_func_name": "music_queue_group",
    "description": "clear the entire queue",
    "aliases": [
      "clear",
      "purge"
    ],
    "category": "music",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music queue empty"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue empty"
  },
  "music_queue_move": {
    "raw_name": "move",
    "func_name": "music_queue_move",
    "parent_func_name": "music_queue_group",
    "description": "move a track to a new position",
    "aliases": [
      "swap"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "pos",
        "type": "int"
      },
      {
        "name": "new_pos",
        "type": "int"
      }
    ],
    "examples": [
      "!music queue move [pos] [new_pos]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue move"
  },
  "music_queue_remove": {
    "raw_name": "remove",
    "func_name": "music_queue_remove",
    "parent_func_name": "music_queue_group",
    "description": "remove a track by position",
    "aliases": [
      "rm"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "position",
        "type": "int"
      }
    ],
    "examples": [
      "!music queue remove [position]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue remove"
  },
  "music_queue_shuffle": {
    "raw_name": "shuffle",
    "func_name": "music_queue_shuffle",
    "parent_func_name": "music_queue_group",
    "description": "shuffle the queue",
    "aliases": [
      "qshuffle"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music queue shuffle"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music queue shuffle"
  },
  "music_preset": {
    "raw_name": "preset",
    "func_name": "music_preset_group",
    "parent_func_name": "music_group",
    "description": "apply an audio filter preset",
    "aliases": [
      "presets"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "music preset 8d",
      "music preset acoustic",
      "music preset alien",
      "music preset bassboost",
      "music preset chipmunk",
      "music preset clear",
      "music preset dance",
      "music preset darthvader",
      "music preset dizzy",
      "music preset earrape",
      "music preset electronic",
      "music preset fast",
      "music preset flat",
      "music preset karaoke",
      "music preset metallic",
      "music preset nightcore",
      "music preset pop",
      "music preset rnb",
      "music preset rock",
      "music preset slow",
      "music preset telephone",
      "music preset tremolo",
      "music preset vaporwave",
      "music preset vibrato",
      "music preset wobble"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset"
  },
  "music_preset_vaporwave": {
    "raw_name": "vaporwave",
    "func_name": "preset_vaporwave",
    "parent_func_name": "music_preset_group",
    "description": "low-fidelity, slowed-down aesthetic audio",
    "aliases": [
      "vapor"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset vaporwave"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset vaporwave"
  },
  "music_preset_vibrato": {
    "raw_name": "vibrato",
    "func_name": "preset_vibrato",
    "parent_func_name": "music_preset_group",
    "description": "pulsating pitch variation effect",
    "aliases": [
      "vib"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset vibrato"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset vibrato"
  },
  "music_preset_bassboost": {
    "raw_name": "bassboost",
    "func_name": "preset_bassboost",
    "parent_func_name": "music_preset_group",
    "description": "boost the low-end frequencies",
    "aliases": [
      "bb",
      "bass"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset bassboost"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset bassboost"
  },
  "music_preset_8d": {
    "raw_name": "8d",
    "func_name": "preset_8d",
    "parent_func_name": "music_preset_group",
    "description": "simulated 360-degree rotating audio",
    "aliases": [
      "360",
      "rotate"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset 8d"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset 8d"
  },
  "music_preset_nightcore": {
    "raw_name": "nightcore",
    "func_name": "preset_nightcore",
    "parent_func_name": "music_preset_group",
    "description": "fast-paced, high-pitched audio",
    "aliases": [
      "nc"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset nightcore"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset nightcore"
  },
  "music_preset_karaoke": {
    "raw_name": "karaoke",
    "func_name": "preset_karaoke",
    "parent_func_name": "music_preset_group",
    "description": "suppress vocals for singing along",
    "aliases": [
      "vocal",
      "sing"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset karaoke"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset karaoke"
  },
  "music_preset_pop": {
    "raw_name": "pop",
    "func_name": "preset_pop",
    "parent_func_name": "music_preset_group",
    "description": "optimized for pop music fidelity",
    "aliases": [
      "mod"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset pop"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset pop"
  },
  "music_preset_electronic": {
    "raw_name": "electronic",
    "func_name": "preset_electronic",
    "parent_func_name": "music_preset_group",
    "description": "enhanced bass and treble for EDM",
    "aliases": [
      "edm"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset electronic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset electronic"
  },
  "music_preset_tremolo": {
    "raw_name": "tremolo",
    "func_name": "preset_tremolo",
    "parent_func_name": "music_preset_group",
    "description": "rapid volume fluctuation effect",
    "aliases": [
      "trem"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset tremolo"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset tremolo"
  },
  "music_preset_telephone": {
    "raw_name": "telephone",
    "func_name": "preset_telephone",
    "parent_func_name": "music_preset_group",
    "description": "simulated radio/telephone speaker quality",
    "aliases": [
      "radio"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset telephone"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset telephone"
  },
  "music_preset_earrape": {
    "raw_name": "earrape",
    "func_name": "preset_earrape",
    "parent_func_name": "music_preset_group",
    "description": "extreme distortion and volume (caution!)",
    "aliases": [
      "er",
      "loud",
      "distort"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset earrape"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset earrape"
  },
  "music_preset_slow": {
    "raw_name": "slow",
    "func_name": "preset_slow",
    "parent_func_name": "music_preset_group",
    "description": "reduced playback speed",
    "aliases": [
      "sl",
      "slowmo",
      "slowed"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset slow"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset slow"
  },
  "music_preset_fast": {
    "raw_name": "fast",
    "func_name": "preset_fast",
    "parent_func_name": "music_preset_group",
    "description": "increased playback speed",
    "aliases": [
      "f",
      "speed",
      "fastmo"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset fast"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset fast"
  },
  "music_preset_chipmunk": {
    "raw_name": "chipmunk",
    "func_name": "preset_chipmunk",
    "parent_func_name": "music_preset_group",
    "description": "very high pitch and speed",
    "aliases": [
      "chip"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset chipmunk"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset chipmunk"
  },
  "music_preset_darthvader": {
    "raw_name": "darthvader",
    "func_name": "preset_darthvader",
    "parent_func_name": "music_preset_group",
    "description": "very low pitch effect",
    "aliases": [
      "vader",
      "dv",
      "darth"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset darthvader"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset darthvader"
  },
  "music_preset_alien": {
    "raw_name": "alien",
    "func_name": "preset_alien",
    "parent_func_name": "music_preset_group",
    "description": "metallic, extraterrestrial voice effect",
    "aliases": [
      "al"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset alien"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset alien"
  },
  "music_preset_metallic": {
    "raw_name": "metallic",
    "func_name": "preset_metallic",
    "parent_func_name": "music_preset_group",
    "description": "simulated industrial/metal resonance",
    "aliases": [
      "metal",
      "met"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset metallic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset metallic"
  },
  "music_preset_acoustic": {
    "raw_name": "acoustic",
    "func_name": "preset_acoustic",
    "parent_func_name": "music_preset_group",
    "description": "natural, warm unplugged sound",
    "aliases": [
      "ac"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset acoustic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset acoustic"
  },
  "music_preset_dance": {
    "raw_name": "dance",
    "func_name": "preset_dance",
    "parent_func_name": "music_preset_group",
    "description": "optimized for club and dance beats",
    "aliases": [
      "dc"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset dance"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset dance"
  },
  "music_preset_rock": {
    "raw_name": "rock",
    "func_name": "preset_rock",
    "parent_func_name": "music_preset_group",
    "description": "enhanced presence for rock music",
    "aliases": [
      "rk",
      "classic"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset rock"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset rock"
  },
  "music_preset_rnb": {
    "raw_name": "rnb",
    "func_name": "preset_rnb",
    "parent_func_name": "music_preset_group",
    "description": "warm, balanced profile for R&B",
    "aliases": [
      "rb",
      "soul"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset rnb"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset rnb"
  },
  "music_preset_flat": {
    "raw_name": "flat",
    "func_name": "preset_flat",
    "parent_func_name": "music_preset_group",
    "description": "reset all equalizer bands to zero",
    "aliases": [
      "fl"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset flat"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset flat"
  },
  "music_preset_dizzy": {
    "raw_name": "dizzy",
    "func_name": "preset_dizzy",
    "parent_func_name": "music_preset_group",
    "description": "1.0Hz rotation frequency effect",
    "aliases": [
      "dz"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset dizzy"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset dizzy"
  },
  "music_preset_wobble": {
    "raw_name": "wobble",
    "func_name": "preset_wobble",
    "parent_func_name": "music_preset_group",
    "description": "extreme tremolo/vibrato disorientation",
    "aliases": [
      "wb",
      "wob"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset wobble"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset wobble"
  },
  "music_preset_clear": {
    "raw_name": "clear",
    "func_name": "preset_clear",
    "parent_func_name": "music_preset_group",
    "description": "clear all active audio filters",
    "aliases": [
      "off",
      "none"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!music preset clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\music.py",
    "name": "music preset clear"
  },
  "preset": {
    "raw_name": "preset",
    "func_name": "preset_group",
    "parent_func_name": null,
    "description": "apply an audio filter preset to the player",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "preset 8d",
      "preset acoustic",
      "preset alien",
      "preset bassboost",
      "preset chipmunk",
      "preset clear",
      "preset dance",
      "preset darthvader",
      "preset dizzy",
      "preset earrape",
      "preset electronic",
      "preset fast",
      "preset flat",
      "preset karaoke",
      "preset metallic",
      "preset nightcore",
      "preset pop",
      "preset rnb",
      "preset rock",
      "preset slow",
      "preset telephone",
      "preset tremolo",
      "preset vaporwave",
      "preset vibrato",
      "preset wobble"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset"
  },
  "preset_vaporwave": {
    "raw_name": "vaporwave",
    "func_name": "preset_vaporwave",
    "parent_func_name": "preset_group",
    "description": "low-fidelity, slowed-down aesthetic audio",
    "aliases": [
      "vapor"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset vaporwave"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset vaporwave"
  },
  "preset_vibrato": {
    "raw_name": "vibrato",
    "func_name": "preset_vibrato",
    "parent_func_name": "preset_group",
    "description": "pulsating pitch variation effect",
    "aliases": [
      "vib"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset vibrato"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset vibrato"
  },
  "preset_bassboost": {
    "raw_name": "bassboost",
    "func_name": "preset_bassboost",
    "parent_func_name": "preset_group",
    "description": "boost the low-end frequencies",
    "aliases": [
      "bb",
      "bass"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset bassboost"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset bassboost"
  },
  "preset_8d": {
    "raw_name": "8d",
    "func_name": "preset_8d",
    "parent_func_name": "preset_group",
    "description": "simulated 360-degree rotating audio",
    "aliases": [
      "360",
      "rotate"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset 8d"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset 8d"
  },
  "preset_nightcore": {
    "raw_name": "nightcore",
    "func_name": "preset_nightcore",
    "parent_func_name": "preset_group",
    "description": "fast-paced, high-pitched audio",
    "aliases": [
      "nc"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset nightcore"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset nightcore"
  },
  "preset_karaoke": {
    "raw_name": "karaoke",
    "func_name": "preset_karaoke",
    "parent_func_name": "preset_group",
    "description": "suppress vocals for singing along",
    "aliases": [
      "vocal",
      "sing"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset karaoke"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset karaoke"
  },
  "preset_pop": {
    "raw_name": "pop",
    "func_name": "preset_pop",
    "parent_func_name": "preset_group",
    "description": "optimized for pop music fidelity",
    "aliases": [
      "mod"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset pop"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset pop"
  },
  "preset_electronic": {
    "raw_name": "electronic",
    "func_name": "preset_electronic",
    "parent_func_name": "preset_group",
    "description": "enhanced bass and treble for EDM",
    "aliases": [
      "edm"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset electronic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset electronic"
  },
  "preset_tremolo": {
    "raw_name": "tremolo",
    "func_name": "preset_tremolo",
    "parent_func_name": "preset_group",
    "description": "rapid volume fluctuation effect",
    "aliases": [
      "trem"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset tremolo"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset tremolo"
  },
  "preset_telephone": {
    "raw_name": "telephone",
    "func_name": "preset_telephone",
    "parent_func_name": "preset_group",
    "description": "simulated radio/telephone speaker quality",
    "aliases": [
      "radio"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset telephone"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset telephone"
  },
  "preset_clear": {
    "raw_name": "clear",
    "func_name": "preset_clear",
    "parent_func_name": "preset_group",
    "description": "clear all active audio filters",
    "aliases": [
      "off",
      "none"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset clear"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset clear"
  },
  "preset_earrape": {
    "raw_name": "earrape",
    "func_name": "preset_earrape",
    "parent_func_name": "preset_group",
    "description": "extreme distortion and volume (caution!)",
    "aliases": [
      "er",
      "loud",
      "distort"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset earrape"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset earrape"
  },
  "preset_slow": {
    "raw_name": "slow",
    "func_name": "preset_slow",
    "parent_func_name": "preset_group",
    "description": "reduced playback speed",
    "aliases": [
      "sl",
      "slowmo",
      "slowed"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset slow"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset slow"
  },
  "preset_fast": {
    "raw_name": "fast",
    "func_name": "preset_fast",
    "parent_func_name": "preset_group",
    "description": "increased playback speed",
    "aliases": [
      "f",
      "speed",
      "fastmo"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset fast"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset fast"
  },
  "preset_chipmunk": {
    "raw_name": "chipmunk",
    "func_name": "preset_chipmunk",
    "parent_func_name": "preset_group",
    "description": "very high pitch and speed",
    "aliases": [
      "chip"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset chipmunk"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset chipmunk"
  },
  "preset_darthvader": {
    "raw_name": "darthvader",
    "func_name": "preset_darthvader",
    "parent_func_name": "preset_group",
    "description": "very low pitch effect",
    "aliases": [
      "vader",
      "dv",
      "darth"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset darthvader"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset darthvader"
  },
  "preset_alien": {
    "raw_name": "alien",
    "func_name": "preset_alien",
    "parent_func_name": "preset_group",
    "description": "metallic, extraterrestrial voice effect",
    "aliases": [
      "al"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset alien"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset alien"
  },
  "preset_metallic": {
    "raw_name": "metallic",
    "func_name": "preset_metallic",
    "parent_func_name": "preset_group",
    "description": "simulated industrial/metal resonance",
    "aliases": [
      "metal",
      "met"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset metallic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset metallic"
  },
  "preset_acoustic": {
    "raw_name": "acoustic",
    "func_name": "preset_acoustic",
    "parent_func_name": "preset_group",
    "description": "natural, warm unplugged sound",
    "aliases": [
      "ac"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset acoustic"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset acoustic"
  },
  "preset_dance": {
    "raw_name": "dance",
    "func_name": "preset_dance",
    "parent_func_name": "preset_group",
    "description": "optimized for club and dance beats",
    "aliases": [
      "dc"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset dance"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset dance"
  },
  "preset_rock": {
    "raw_name": "rock",
    "func_name": "preset_rock",
    "parent_func_name": "preset_group",
    "description": "enhanced presence for rock music",
    "aliases": [
      "rk",
      "classic"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset rock"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset rock"
  },
  "preset_rnb": {
    "raw_name": "rnb",
    "func_name": "preset_rnb",
    "parent_func_name": "preset_group",
    "description": "warm, balanced profile for R&B",
    "aliases": [
      "rb",
      "soul"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset rnb"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset rnb"
  },
  "preset_flat": {
    "raw_name": "flat",
    "func_name": "preset_flat",
    "parent_func_name": "preset_group",
    "description": "reset all equalizer bands to zero",
    "aliases": [
      "fl"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset flat"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset flat"
  },
  "preset_dizzy": {
    "raw_name": "dizzy",
    "func_name": "preset_dizzy",
    "parent_func_name": "preset_group",
    "description": "1.0Hz rotation frequency effect",
    "aliases": [
      "dz"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset dizzy"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset dizzy"
  },
  "preset_wobble": {
    "raw_name": "wobble",
    "func_name": "preset_wobble",
    "parent_func_name": "preset_group",
    "description": "extreme tremolo/vibrato disorientation",
    "aliases": [
      "wb",
      "wob"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!preset wobble"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "preset wobble"
  },
  "vapor": {
    "raw_name": "vapor",
    "func_name": "vapor_shorthand",
    "parent_func_name": null,
    "description": "low-fidelity, slowed-down aesthetic audio shorthand",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!vapor"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "vapor"
  },
  "vib": {
    "raw_name": "vib",
    "func_name": "vib_shorthand",
    "parent_func_name": null,
    "description": "pulsating pitch variation effect shorthand",
    "aliases": [],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!vib"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "vib"
  },
  "sl": {
    "raw_name": "sl",
    "func_name": "slow_shorthand",
    "parent_func_name": null,
    "description": "shorthand for slow preset",
    "aliases": [
      "slowmo",
      "slowed"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!sl"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "sl"
  },
  "rk": {
    "raw_name": "rk",
    "func_name": "rock_shorthand",
    "parent_func_name": null,
    "description": "shorthand for rock preset",
    "aliases": [
      "classic"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!rk"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\presets.py",
    "name": "rk"
  },
  "queue": {
    "raw_name": "queue",
    "func_name": "queue_group",
    "parent_func_name": null,
    "description": "queue management",
    "aliases": [
      "q"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!queue"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "queue empty",
      "queue move",
      "queue remove",
      "queue shuffle",
      "queue view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue"
  },
  "queue_view": {
    "raw_name": "view",
    "func_name": "queue_view_cmd",
    "parent_func_name": "queue_group",
    "description": "view the queue",
    "aliases": [
      "list"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!queue view"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue view"
  },
  "queue_empty": {
    "raw_name": "empty",
    "func_name": "queue_empty",
    "parent_func_name": "queue_group",
    "description": "clear the entire queue",
    "aliases": [
      "clear",
      "purge"
    ],
    "category": "music",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!queue empty"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue empty"
  },
  "queue_move": {
    "raw_name": "move",
    "func_name": "queue_move",
    "parent_func_name": "queue_group",
    "description": "move a track to a new position",
    "aliases": [
      "swap"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "pos",
        "type": "int"
      },
      {
        "name": "new_pos",
        "type": "int"
      }
    ],
    "examples": [
      "!queue move [pos] [new_pos]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue move"
  },
  "queue_remove": {
    "raw_name": "remove",
    "func_name": "queue_remove",
    "parent_func_name": "queue_group",
    "description": "remove a track by position",
    "aliases": [
      "rm"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "position",
        "type": "int"
      }
    ],
    "examples": [
      "!queue remove [position]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue remove"
  },
  "queue_shuffle": {
    "raw_name": "shuffle",
    "func_name": "queue_shuffle",
    "parent_func_name": "queue_group",
    "description": "shuffle the queue",
    "aliases": [
      "qshuffle"
    ],
    "category": "music",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!queue shuffle"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\music\\queue_cmds.py",
    "name": "queue shuffle"
  }
};