// AUTO-GENERATED: Server commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const SERVER_COMMANDS: Record<string, Command> = {
  "cleanup": {
    "raw_name": "cleanup",
    "func_name": "cleanup_group",
    "parent_func_name": "admin_group",
    "description": "clean up unused roles, channels, and bots",
    "aliases": [
      "clean",
      "adminclean"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!cleanup"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "cleanup bots",
      "cleanup channels",
      "cleanup duplicates",
      "cleanup roles"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "cleanup"
  },
  "cleanup_roles": {
    "raw_name": "roles",
    "func_name": "cleanup_roles",
    "parent_func_name": "cleanup_group",
    "description": "find and remove roles with no members",
    "aliases": [
      "emptyroles",
      "unused-roles"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!cleanup roles"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "cleanup roles"
  },
  "cleanup_channels": {
    "raw_name": "channels",
    "func_name": "cleanup_channels",
    "parent_func_name": "cleanup_group",
    "description": "find channels with no recent activity",
    "aliases": [
      "unused",
      "inactive"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!cleanup channels"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "cleanup channels"
  },
  "cleanup_bots": {
    "raw_name": "bots",
    "func_name": "cleanup_bots",
    "parent_func_name": "cleanup_group",
    "description": "list all bots and what they can do",
    "aliases": [
      "botlist",
      "bot-list"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!cleanup bots"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "cleanup bots"
  },
  "cleanup_duplicates": {
    "raw_name": "duplicates",
    "func_name": "cleanup_duplicates",
    "parent_func_name": "cleanup_group",
    "description": "find duplicate roles and channels",
    "aliases": [
      "dupes",
      "duplicate"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!cleanup duplicates"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "cleanup duplicates"
  },
  "announce": {
    "raw_name": "announce",
    "func_name": "announce",
    "parent_func_name": "admin_group",
    "description": "send an announcement to a channel",
    "aliases": [
      "announcement",
      "serverannounce"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "message",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "examples": [
      "!announce <message> [channel]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "announce"
  },
  "notes": {
    "raw_name": "notes",
    "func_name": "notes_group",
    "parent_func_name": "admin_group",
    "description": "keep notes about users",
    "aliases": [
      "note",
      "adminnotes"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!notes"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "notes add",
      "notes remove",
      "notes view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "notes"
  },
  "notes_add": {
    "raw_name": "add",
    "func_name": "notes_add",
    "parent_func_name": "notes_group",
    "description": "add a note about someone",
    "aliases": [
      "create",
      "new"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      },
      {
        "name": "note",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!notes add <user> <note>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "notes add"
  },
  "notes_remove": {
    "raw_name": "remove",
    "func_name": "notes_remove",
    "parent_func_name": "notes_group",
    "description": "delete a note",
    "aliases": [
      "delete",
      "rm"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      },
      {
        "name": "note_id",
        "type": "int"
      }
    ],
    "optional_args": [],
    "examples": [
      "!notes remove <user> <note_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "notes remove"
  },
  "notes_view": {
    "raw_name": "view",
    "func_name": "notes_view",
    "parent_func_name": "notes_group",
    "description": "see notes about someone",
    "aliases": [
      "list",
      "show"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      }
    ],
    "optional_args": [],
    "examples": [
      "!notes view <user>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "notes view"
  },
  "recent": {
    "raw_name": "recent",
    "func_name": "recent_group",
    "parent_func_name": "admin_group",
    "description": "View recent moderation actions",
    "aliases": [
      "recentactions",
      "recentmods"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!recent"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "recent bans",
      "recent kicks"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "recent"
  },
  "recent_bans": {
    "raw_name": "bans",
    "func_name": "recent_bans",
    "parent_func_name": "recent_group",
    "description": "Show recent bans with reasons and moderators",
    "aliases": [
      "ban",
      "banned"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!recent bans"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "recent bans"
  },
  "recent_kicks": {
    "raw_name": "kicks",
    "func_name": "recent_kicks",
    "parent_func_name": "recent_group",
    "description": "Show recent kicks with reasons and moderators",
    "aliases": [
      "kick",
      "kicked"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!recent kicks"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "recent kicks"
  },
  "viewwarnings": {
    "raw_name": "viewwarnings",
    "func_name": "warnings_list",
    "parent_func_name": "admin_group",
    "description": "View all warnings for a user",
    "aliases": [
      "warninglist",
      "checkwarnings",
      "showwarnings"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      }
    ],
    "optional_args": [],
    "examples": [
      "!viewwarnings <user>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "viewwarnings"
  },
  "history": {
    "raw_name": "history",
    "func_name": "moderation_history",
    "parent_func_name": "admin_group",
    "description": "View complete moderation history for a user",
    "aliases": [
      "modhistory",
      "modlogs"
    ],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      }
    ],
    "optional_args": [],
    "examples": [
      "!history <user>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\admin.py",
    "name": "history"
  },
  "logs": {
    "raw_name": "logs",
    "func_name": "logs",
    "parent_func_name": null,
    "description": "set up logging for your server",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "logs aio",
      "logs disable",
      "logs ignore",
      "logs setup"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs"
  },
  "logs_disable": {
    "raw_name": "disable",
    "func_name": "logs_disable",
    "parent_func_name": "logs",
    "description": "turn off all logs",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs disable"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs disable"
  },
  "logs_setup": {
    "raw_name": "setup",
    "func_name": "logs_setup_interactive",
    "parent_func_name": "logs",
    "description": "set up logs step by step",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs setup"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs setup"
  },
  "logs_ignore": {
    "raw_name": "ignore",
    "func_name": "logs_ignore",
    "parent_func_name": "logs",
    "description": "ignore certain stuff from logs",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs ignore"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "logs ignore channel",
      "logs ignore list",
      "logs ignore role",
      "logs ignore user"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs ignore"
  },
  "logs_ignore_role": {
    "raw_name": "role",
    "func_name": "ignore_role",
    "parent_func_name": "logs_ignore",
    "description": "ignore a role from logs",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "role",
        "type": "Role"
      }
    ],
    "optional_args": [],
    "examples": [
      "!logs ignore role <role>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs ignore role"
  },
  "logs_ignore_channel": {
    "raw_name": "channel",
    "func_name": "ignore_channel",
    "parent_func_name": "logs_ignore",
    "description": "ignore a channel from logs",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "channel",
        "type": "TextChannel"
      }
    ],
    "optional_args": [],
    "examples": [
      "!logs ignore channel <channel>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs ignore channel"
  },
  "logs_ignore_user": {
    "raw_name": "user",
    "func_name": "ignore_user",
    "parent_func_name": "logs_ignore",
    "description": "ignore a user from logs",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "user",
        "type": "User"
      }
    ],
    "optional_args": [],
    "examples": [
      "!logs ignore user <user>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs ignore user"
  },
  "logs_ignore_list": {
    "raw_name": "list",
    "func_name": "ignore_list",
    "parent_func_name": "logs_ignore",
    "description": "see what's ignored",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs ignore list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs ignore list"
  },
  "logs_aio": {
    "raw_name": "aio",
    "func_name": "logs_aio",
    "parent_func_name": "logs",
    "description": "auto-setup all logging channels",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Channels",
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!logs aio"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\logging.py",
    "name": "logs aio"
  },
  "prefixes": {
    "raw_name": "prefixes",
    "func_name": "prefixes_group",
    "parent_func_name": null,
    "description": "server prefix settings",
    "aliases": [
      "prefix"
    ],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!prefixes"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "prefixes add",
      "prefixes list",
      "prefixes noprefix",
      "prefixes remove",
      "prefixes self"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes"
  },
  "prefixes_add": {
    "raw_name": "add",
    "func_name": "prefix_add",
    "parent_func_name": "prefixes_group",
    "description": "add a server prefix",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "prefix",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!prefixes add <prefix>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes add"
  },
  "prefixes_remove": {
    "raw_name": "remove",
    "func_name": "prefix_remove",
    "parent_func_name": "prefixes_group",
    "description": "remove a prefix",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "prefix",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!prefixes remove <prefix>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes remove"
  },
  "prefixes_list": {
    "raw_name": "list",
    "func_name": "prefix_list",
    "parent_func_name": "prefixes_group",
    "description": "see all prefixes",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!prefixes list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes list"
  },
  "prefixes_self": {
    "raw_name": "self",
    "func_name": "prefix_self",
    "parent_func_name": "prefixes_group",
    "description": "set your own personal prefix",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [
      {
        "name": "prefix",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!prefixes self <prefix>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes self"
  },
  "prefixes_noprefix": {
    "raw_name": "noprefix",
    "func_name": "prefix_noprefix",
    "parent_func_name": "prefixes_group",
    "description": "use commands without a prefix",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!prefixes noprefix"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\prefixes.py",
    "name": "prefixes noprefix"
  },
  "settings": {
    "raw_name": "settings",
    "func_name": "settings_group",
    "parent_func_name": null,
    "description": "server settings",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!settings"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "settings backup"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings"
  },
  "settings_backup": {
    "raw_name": "backup",
    "func_name": "backup_group",
    "parent_func_name": "settings_group",
    "description": "server backups",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!settings backup"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": true,
    "subcommands": [
      "settings backup create",
      "settings backup delete",
      "settings backup list",
      "settings backup restore"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings backup"
  },
  "settings_backup_create": {
    "raw_name": "create",
    "func_name": "backup_create",
    "parent_func_name": "backup_group",
    "description": "save a backup",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!settings backup create"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings backup create"
  },
  "settings_backup_list": {
    "raw_name": "list",
    "func_name": "backup_list",
    "parent_func_name": "backup_group",
    "description": "see your backups",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!settings backup list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings backup list"
  },
  "settings_backup_restore": {
    "raw_name": "restore",
    "func_name": "backup_restore",
    "parent_func_name": "backup_group",
    "description": "restore from a backup",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "backup_id",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!settings backup restore <backup_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings backup restore"
  },
  "settings_backup_delete": {
    "raw_name": "delete",
    "func_name": "backup_delete",
    "parent_func_name": "backup_group",
    "description": "delete a backup",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator"
    ],
    "required_args": [
      {
        "name": "backup_id",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!settings backup delete <backup_id>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "settings backup delete"
  },
  "customise": {
    "raw_name": "customise",
    "func_name": "customise_group",
    "parent_func_name": null,
    "description": "customize how the bot looks",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!customise"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "customise banner",
      "customise bio",
      "customise name",
      "customise pfp"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "customise"
  },
  "customise_pfp": {
    "raw_name": "pfp",
    "func_name": "customise_banner",
    "parent_func_name": "customise_group",
    "description": "change the bot's pfp",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator",
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "image_url",
        "type": "str"
      },
      {
        "name": "attachment",
        "type": "Attachment"
      }
    ],
    "examples": [
      "!customise pfp [image_url] [attachment]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "customise pfp"
  },
  "customise_bio": {
    "raw_name": "bio",
    "func_name": "customise_bio",
    "parent_func_name": "customise_group",
    "description": "change the bot's bio",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator",
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "bio",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!customise bio <bio>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "customise bio"
  },
  "customise_banner": {
    "raw_name": "banner",
    "func_name": "customise_banner",
    "parent_func_name": "customise_group",
    "description": "change the bot's banner",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator",
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "image_url",
        "type": "str"
      },
      {
        "name": "attachment",
        "type": "Attachment"
      }
    ],
    "examples": [
      "!customise banner [image_url] [attachment]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "customise banner"
  },
  "customise_name": {
    "raw_name": "name",
    "func_name": "customise_name",
    "parent_func_name": "customise_group",
    "description": "change the bot's name",
    "aliases": [],
    "category": "server",
    "permissions": [
      "Administrator",
      "Manage Guild"
    ],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!customise name <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\settings.py",
    "name": "customise name"
  },
  "stats": {
    "raw_name": "stats",
    "func_name": "stats",
    "parent_func_name": null,
    "description": "server stats",
    "aliases": [],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!stats"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "stats messages",
      "stats server",
      "stats topmessages",
      "stats user"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\stats.py",
    "name": "stats"
  },
  "stats_user": {
    "raw_name": "user",
    "func_name": "user_stats",
    "parent_func_name": "stats",
    "description": "check out a user's stats",
    "aliases": [
      "profile",
      "info",
      "whois"
    ],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!stats user [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\stats.py",
    "name": "stats user"
  },
  "stats_messages": {
    "raw_name": "messages",
    "func_name": "message_stats",
    "parent_func_name": "stats",
    "description": "see message stats with a graph",
    "aliases": [
      "msgcount",
      "activity",
      "msgs"
    ],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!stats messages [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\stats.py",
    "name": "stats messages"
  },
  "stats_topmessages": {
    "raw_name": "topmessages",
    "func_name": "top_messages",
    "parent_func_name": "stats",
    "description": "who's chatting the most",
    "aliases": [
      "msgtop",
      "chatters",
      "topmsg"
    ],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!stats topmessages"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\stats.py",
    "name": "stats topmessages"
  },
  "stats_server": {
    "raw_name": "server",
    "func_name": "server_stats",
    "parent_func_name": "stats",
    "description": "overall server stats",
    "aliases": [
      "serverstats",
      "guildstats"
    ],
    "category": "server",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!stats server"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\server\\stats.py",
    "name": "stats server"
  }
};