// AUTO-GENERATED: Utility commands from plugins
// DO NOT EDIT MANUALLY - Generated by generate_commands.py

export interface Command {
  name: string;
  description: string;
  aliases: string[];
  category: string;
  permissions: string[];
  required_args: any[];
  optional_args: any[];
  examples: string[];
  subcommands?: string[];
  has_prefix: boolean;
  has_slash: boolean;
  is_group?: boolean;
}

export const UTILITY_COMMANDS: Record<string, Command> = {
  "embed": {
    "raw_name": "embed",
    "func_name": "embed_group",
    "parent_func_name": null,
    "description": "manage and create custom embeds",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!embed"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "embed create",
      "embed delete",
      "embed list",
      "embed save",
      "embed send"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed"
  },
  "embed_create": {
    "raw_name": "create",
    "func_name": "embed_create",
    "parent_func_name": "embed_group",
    "description": "open an interactive embed creator",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!embed create"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed create"
  },
  "embed_send": {
    "raw_name": "send",
    "func_name": "embed_send",
    "parent_func_name": "embed_group",
    "description": "send an embed using a script",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "script",
        "type": "str"
      }
    ],
    "examples": [
      "!embed send [script]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed send"
  },
  "embed_save": {
    "raw_name": "save",
    "func_name": "embed_save",
    "parent_func_name": "embed_group",
    "description": "save an embed script for future use",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      },
      {
        "name": "script",
        "type": "str"
      }
    ],
    "examples": [
      "!embed save [name] [script]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed save"
  },
  "embed_list": {
    "raw_name": "list",
    "func_name": "embed_list",
    "parent_func_name": "embed_group",
    "description": "list your saved embeds",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!embed list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed list"
  },
  "variables": {
    "raw_name": "variables",
    "func_name": "variables_command",
    "parent_func_name": null,
    "description": "show all available script variables",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!variables"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "variables"
  },
  "embed_delete": {
    "raw_name": "delete",
    "func_name": "embed_delete",
    "parent_func_name": "embed_group",
    "description": "delete a saved embed by id",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "embed_id",
        "type": "int"
      }
    ],
    "examples": [
      "!embed delete [embed_id]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "embed delete"
  },
  "ce": {
    "raw_name": "ce",
    "func_name": "ce_command",
    "parent_func_name": null,
    "description": "send an embed using a script (prefix only)",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Embed Links"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "script",
        "type": "str"
      }
    ],
    "examples": [
      "!ce [script]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\embeds.py",
    "name": "ce"
  },
  "get": {
    "raw_name": "get",
    "func_name": "get_group",
    "parent_func_name": null,
    "description": "grab user and server info",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!get"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "get avatar",
      "get banner",
      "get device",
      "get profile",
      "get serverbanner",
      "get servericon",
      "get serverinfo"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get"
  },
  "get_avatar": {
    "raw_name": "avatar",
    "func_name": "get_avatar",
    "parent_func_name": "get_group",
    "description": "show someone's pfp",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!get avatar [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get avatar"
  },
  "get_banner": {
    "raw_name": "banner",
    "func_name": "get_banner",
    "parent_func_name": "get_group",
    "description": "show someone's banner",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!get banner [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get banner"
  },
  "get_profile": {
    "raw_name": "profile",
    "func_name": "get_profile",
    "parent_func_name": "get_group",
    "description": "see info about a user",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!get profile [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get profile"
  },
  "get_device": {
    "raw_name": "device",
    "func_name": "get_device",
    "parent_func_name": "get_group",
    "description": "see what device someone's on",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!get device [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get device"
  },
  "get_serverinfo": {
    "raw_name": "serverinfo",
    "func_name": "get_serverinfo",
    "parent_func_name": "get_group",
    "description": "see info about this server",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!get serverinfo"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get serverinfo"
  },
  "get_servericon": {
    "raw_name": "servericon",
    "func_name": "get_servericon",
    "parent_func_name": "get_group",
    "description": "show the server icon",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!get servericon"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get servericon"
  },
  "get_serverbanner": {
    "raw_name": "serverbanner",
    "func_name": "get_serverbanner",
    "parent_func_name": "get_group",
    "description": "show the server banner",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!get serverbanner"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\get.py",
    "name": "get serverbanner"
  },
  "help": {
    "raw_name": "help",
    "func_name": "help_command",
    "parent_func_name": null,
    "description": "show all commands and how to use them",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "command",
        "type": "str"
      }
    ],
    "examples": [
      "!help [command]"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\help.py",
    "name": "help"
  },
  "pagination": {
    "raw_name": "pagination",
    "func_name": "pagination",
    "parent_func_name": null,
    "description": "Manage multi-page embed messages",
    "aliases": [
      "page",
      "pages",
      "pg"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!pagination"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "pagination add",
      "pagination delete",
      "pagination list",
      "pagination remove",
      "pagination reset",
      "pagination restorereactions",
      "pagination set",
      "pagination update"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination"
  },
  "pagination_set": {
    "raw_name": "set",
    "func_name": "pagination_set",
    "parent_func_name": "pagination",
    "description": "Set up an existing embed to be paginated",
    "aliases": [
      "create",
      "new"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      }
    ],
    "examples": [
      "!pagination set [message_ref]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination set"
  },
  "pagination_add": {
    "raw_name": "add",
    "func_name": "pagination_add",
    "parent_func_name": "pagination",
    "description": "Add a page to a pagination embed",
    "aliases": [
      "addpage"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      },
      {
        "name": "embed_code",
        "type": "str"
      }
    ],
    "examples": [
      "!pagination add [message_ref] [embed_code]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination add"
  },
  "pagination_remove": {
    "raw_name": "remove",
    "func_name": "pagination_remove",
    "parent_func_name": "pagination",
    "description": "Remove a page from a pagination embed",
    "aliases": [
      "removepage",
      "rm"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      },
      {
        "name": "page_id",
        "type": "int"
      }
    ],
    "examples": [
      "!pagination remove [message_ref] [page_id]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination remove"
  },
  "pagination_update": {
    "raw_name": "update",
    "func_name": "pagination_update",
    "parent_func_name": "pagination",
    "description": "Update an existing page on pagination embed",
    "aliases": [
      "edit",
      "modify"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      },
      {
        "name": "page_id",
        "type": "int"
      },
      {
        "name": "embed_code",
        "type": "str"
      }
    ],
    "examples": [
      "!pagination update [message_ref] [page_id] [embed_code]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination update"
  },
  "pagination_delete": {
    "raw_name": "delete",
    "func_name": "pagination_delete",
    "parent_func_name": "pagination",
    "description": "Delete a pagination embed entirely",
    "aliases": [
      "del"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      }
    ],
    "examples": [
      "!pagination delete [message_ref]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination delete"
  },
  "pagination_list": {
    "raw_name": "list",
    "func_name": "pagination_list",
    "parent_func_name": "pagination",
    "description": "View all existing pagination embeds",
    "aliases": [
      "show",
      "ls"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!pagination list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination list"
  },
  "pagination_reset": {
    "raw_name": "reset",
    "func_name": "pagination_reset",
    "parent_func_name": "pagination",
    "description": "Remove every existing pagination in guild",
    "aliases": [
      "clear",
      "deleteall"
    ],
    "category": "utility",
    "permissions": [
      "Administrator"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!pagination reset"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination reset"
  },
  "pagination_restorereactions": {
    "raw_name": "restorereactions",
    "func_name": "pagination_restore",
    "parent_func_name": "pagination",
    "description": "Restore reactions to an existing pagination",
    "aliases": [
      "restore",
      "fix"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "message_ref",
        "type": "str"
      }
    ],
    "examples": [
      "!pagination restorereactions [message_ref]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\pagination.py",
    "name": "pagination restorereactions"
  },
  "tag": {
    "raw_name": "tag",
    "func_name": "tag_group",
    "parent_func_name": null,
    "description": "save and use text snippets",
    "aliases": [
      "tags"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!tag [name]"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "tag alias",
      "tag create",
      "tag delete",
      "tag edit",
      "tag info",
      "tag list",
      "tag lock",
      "tag owner",
      "tag random",
      "tag raw",
      "tag search",
      "tag show",
      "tag top",
      "tag transfer",
      "tag unalias",
      "tag unlock",
      "tag variables"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag"
  },
  "tag_create": {
    "raw_name": "create",
    "func_name": "tag_create",
    "parent_func_name": "tag_group",
    "description": "create a new tag",
    "aliases": [
      "add",
      "new"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      },
      {
        "name": "content",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag create <name> <content>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag create"
  },
  "tag_edit": {
    "raw_name": "edit",
    "func_name": "tag_edit",
    "parent_func_name": "tag_group",
    "description": "edit an existing tag",
    "aliases": [
      "update",
      "change"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      },
      {
        "name": "content",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag edit <name> <content>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag edit"
  },
  "tag_delete": {
    "raw_name": "delete",
    "func_name": "tag_delete",
    "parent_func_name": "tag_group",
    "description": "delete a tag",
    "aliases": [
      "remove",
      "del"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag delete <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag delete"
  },
  "tag_show": {
    "raw_name": "show",
    "func_name": "tag_show",
    "parent_func_name": "tag_group",
    "description": "display a tag",
    "aliases": [
      "view",
      "get"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag show <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag show"
  },
  "tag_list": {
    "raw_name": "list",
    "func_name": "tag_list",
    "parent_func_name": "tag_group",
    "description": "list all tags",
    "aliases": [
      "all",
      "ls"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!tag list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag list"
  },
  "tag_info": {
    "raw_name": "info",
    "func_name": "tag_info",
    "parent_func_name": "tag_group",
    "description": "show tag metadata",
    "aliases": [
      "details",
      "meta"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag info <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag info"
  },
  "tag_raw": {
    "raw_name": "raw",
    "func_name": "tag_raw",
    "parent_func_name": "tag_group",
    "description": "show raw tag content",
    "aliases": [
      "source",
      "plain"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag raw <name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag raw"
  },
  "tag_search": {
    "raw_name": "search",
    "func_name": "tag_search",
    "parent_func_name": "tag_group",
    "description": "search for tags",
    "aliases": [
      "find",
      "lookup"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "query",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag search <query>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag search"
  },
  "tag_alias": {
    "raw_name": "alias",
    "func_name": "tag_alias",
    "parent_func_name": "tag_group",
    "description": "create tag alias",
    "aliases": [
      "shortcut",
      "link"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "tag_name",
        "type": "str"
      },
      {
        "name": "alias_name",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!tag alias <tag_name> <alias_name>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag alias"
  },
  "tag_unalias": {
    "raw_name": "unalias",
    "func_name": "tag_unalias",
    "parent_func_name": "tag_group",
    "description": "remove tag alias",
    "aliases": [
      "unlink",
      "removealias"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "alias_name",
        "type": "str"
      }
    ],
    "examples": [
      "!tag unalias [alias_name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag unalias"
  },
  "tag_owner": {
    "raw_name": "owner",
    "func_name": "tag_owner",
    "parent_func_name": "tag_group",
    "description": "show tag owner",
    "aliases": [
      "creator",
      "author"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!tag owner [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag owner"
  },
  "tag_transfer": {
    "raw_name": "transfer",
    "func_name": "tag_transfer",
    "parent_func_name": "tag_group",
    "description": "transfer tag ownership",
    "aliases": [
      "give",
      "handoff"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      },
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!tag transfer [name] [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag transfer"
  },
  "tag_lock": {
    "raw_name": "lock",
    "func_name": "tag_lock",
    "parent_func_name": "tag_group",
    "description": "lock a tag",
    "aliases": [
      "protect",
      "freeze"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!tag lock [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag lock"
  },
  "tag_unlock": {
    "raw_name": "unlock",
    "func_name": "tag_unlock",
    "parent_func_name": "tag_group",
    "description": "unlock a tag",
    "aliases": [
      "unprotect",
      "unfreeze"
    ],
    "category": "utility",
    "permissions": [
      "Manage Messages"
    ],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!tag unlock [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag unlock"
  },
  "tag_random": {
    "raw_name": "random",
    "func_name": "tag_random",
    "parent_func_name": "tag_group",
    "description": "show random tag",
    "aliases": [
      "surprise",
      "shuffle"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!tag random"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag random"
  },
  "tag_top": {
    "raw_name": "top",
    "func_name": "tag_top",
    "parent_func_name": "tag_group",
    "description": "show most used tags",
    "aliases": [
      "popular",
      "best"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!tag top"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag top"
  },
  "tag_variables": {
    "raw_name": "variables",
    "func_name": "tag_variables",
    "parent_func_name": "tag_group",
    "description": "show supported tag variables",
    "aliases": [
      "vars",
      "placeholders"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!tag variables"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tags.py",
    "name": "tag variables"
  },
  "timezone": {
    "raw_name": "timezone",
    "func_name": "timezone_group",
    "parent_func_name": null,
    "description": "Manage your timezone settings",
    "aliases": [
      "tz"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!timezone"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "timezone list",
      "timezone set",
      "timezone view"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tz.py",
    "name": "timezone"
  },
  "timezone_set": {
    "raw_name": "set",
    "func_name": "timezone_set",
    "parent_func_name": "timezone_group",
    "description": "Set your timezone",
    "aliases": [
      "update"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "timezone",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!timezone set <timezone>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tz.py",
    "name": "timezone set"
  },
  "timezone_list": {
    "raw_name": "list",
    "func_name": "timezone_list",
    "parent_func_name": "timezone_group",
    "description": "View timezones of users in this server",
    "aliases": [
      "server"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!timezone list"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tz.py",
    "name": "timezone list"
  },
  "timezone_view": {
    "raw_name": "view",
    "func_name": "timezone_view",
    "parent_func_name": "timezone_group",
    "description": "Check your timezone or another user's",
    "aliases": [
      "check",
      "get"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!timezone view [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\tz.py",
    "name": "timezone view"
  },
  "utility_botinfo": {
    "raw_name": "botinfo",
    "func_name": "botinfo",
    "parent_func_name": "utility_group",
    "description": "shows detailed information about the bot",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility botinfo"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility botinfo"
  },
  "utility": {
    "raw_name": "utility",
    "func_name": "utility_group",
    "parent_func_name": null,
    "description": "handy tools for your server",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "utility botinfo",
      "utility changelog",
      "utility checkdev",
      "utility myid",
      "utility ping",
      "utility poll",
      "utility qr",
      "utility reminder",
      "utility reminders",
      "utility scannsfw"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility"
  },
  "utility_ping": {
    "raw_name": "ping",
    "func_name": "ping",
    "parent_func_name": "utility_group",
    "description": "check if bot is alive",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility ping"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility ping"
  },
  "utility_changelog": {
    "raw_name": "changelog",
    "func_name": "changelog",
    "parent_func_name": "utility_group",
    "description": "see what's new",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility changelog"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility changelog"
  },
  "utility_myid": {
    "raw_name": "myid",
    "func_name": "my_id",
    "parent_func_name": "utility_group",
    "description": "see your discord user id number",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility myid"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility myid"
  },
  "utility_checkdev": {
    "raw_name": "checkdev",
    "func_name": "check_dev",
    "parent_func_name": "utility_group",
    "description": "check if you have bot developer permissions",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility checkdev"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility checkdev"
  },
  "utility_poll": {
    "raw_name": "poll",
    "func_name": "poll",
    "parent_func_name": "utility_group",
    "description": "creates a voting poll where everyone can pick their favorite",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "question",
        "type": "str"
      }
    ],
    "optional_args": [
      {
        "name": "options",
        "type": "str"
      },
      {
        "name": "duration",
        "type": "str"
      }
    ],
    "examples": [
      "!utility poll <question> [options] [duration]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility poll"
  },
  "utility_reminder": {
    "raw_name": "reminder",
    "func_name": "reminder",
    "parent_func_name": "utility_group",
    "description": "sets a reminder so you remember important things later",
    "aliases": [
      "remind",
      "remindme"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "duration",
        "type": "str"
      },
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!utility reminder <duration> <text>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility reminder"
  },
  "utility_reminders": {
    "raw_name": "reminders",
    "func_name": "list_reminders",
    "parent_func_name": "utility_group",
    "description": "shows all reminders you have set up",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!utility reminders"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility reminders"
  },
  "utility_qr": {
    "raw_name": "qr",
    "func_name": "qr_code",
    "parent_func_name": "utility_group",
    "description": "makes a QR code picture from your text",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [
      {
        "name": "text",
        "type": "str"
      }
    ],
    "optional_args": [],
    "examples": [
      "!utility qr <text>"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility qr"
  },
  "utility_scannsfw": {
    "raw_name": "scannsfw",
    "func_name": "scannsfw",
    "parent_func_name": "utility_group",
    "description": "checks if a picture is appropriate for everyone",
    "aliases": [
      "nsfw",
      "scan"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      },
      {
        "name": "file",
        "type": "str"
      }
    ],
    "examples": [
      "!utility scannsfw [user] [file]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\utility.py",
    "name": "utility scannsfw"
  },
  "voicemaster": {
    "raw_name": "voicemaster",
    "func_name": "voicemaster_group",
    "parent_func_name": null,
    "description": "voice channel management system",
    "aliases": [
      "vm",
      "vc"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster"
    ],
    "has_prefix": true,
    "has_slash": true,
    "is_group": true,
    "subcommands": [
      "voicemaster claim",
      "voicemaster delete",
      "voicemaster deny",
      "voicemaster drag",
      "voicemaster information",
      "voicemaster limit",
      "voicemaster lock",
      "voicemaster permit",
      "voicemaster rename",
      "voicemaster reset",
      "voicemaster reveal",
      "voicemaster setup",
      "voicemaster unlock"
    ],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster"
  },
  "voicemaster_reset": {
    "raw_name": "reset",
    "func_name": "reset_voicemaster",
    "parent_func_name": "voicemaster_group",
    "description": "reset voicemaster configuration",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster reset"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster reset"
  },
  "voicemaster_setup": {
    "raw_name": "setup",
    "func_name": "setup_voicemaster",
    "parent_func_name": "voicemaster_group",
    "description": "set up voicemaster system",
    "aliases": [],
    "category": "utility",
    "permissions": [
      "Manage Guild"
    ],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster setup"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster setup"
  },
  "voicemaster_unlock": {
    "raw_name": "unlock",
    "func_name": "unlock_vc",
    "parent_func_name": "voicemaster_group",
    "description": "unlock your temporary voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster unlock"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster unlock"
  },
  "voicemaster_lock": {
    "raw_name": "lock",
    "func_name": "lock_vc",
    "parent_func_name": "voicemaster_group",
    "description": "lock your temporary voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster lock"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster lock"
  },
  "voicemaster_reveal": {
    "raw_name": "reveal",
    "func_name": "reveal_vc",
    "parent_func_name": "voicemaster_group",
    "description": "reveal your hidden voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster reveal"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster reveal"
  },
  "voicemaster_permit": {
    "raw_name": "permit",
    "func_name": "permit_user",
    "parent_func_name": "voicemaster_group",
    "description": "allow a user in your voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!voicemaster permit [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster permit"
  },
  "voicemaster_deny": {
    "raw_name": "deny",
    "func_name": "deny_user",
    "parent_func_name": "voicemaster_group",
    "description": "deny a user from your voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!voicemaster deny [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster deny"
  },
  "voicemaster_claim": {
    "raw_name": "claim",
    "func_name": "claim_vc",
    "parent_func_name": "voicemaster_group",
    "description": "claim an unowned temporary voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster claim"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster claim"
  },
  "voicemaster_drag": {
    "raw_name": "drag",
    "func_name": "drag_user",
    "parent_func_name": "voicemaster_group",
    "description": "drag a user to your voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "user",
        "type": "Member"
      }
    ],
    "examples": [
      "!voicemaster drag [user]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster drag"
  },
  "voicemaster_delete": {
    "raw_name": "delete",
    "func_name": "delete_vc",
    "parent_func_name": "voicemaster_group",
    "description": "delete your temporary voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster delete"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster delete"
  },
  "voicemaster_information": {
    "raw_name": "information",
    "func_name": "vc_info",
    "parent_func_name": "voicemaster_group",
    "description": "view information about your voice channel",
    "aliases": [
      "info"
    ],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [],
    "examples": [
      "!voicemaster information"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster information"
  },
  "voicemaster_limit": {
    "raw_name": "limit",
    "func_name": "set_limit",
    "parent_func_name": "voicemaster_group",
    "description": "set the member limit for your voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "limit",
        "type": "int"
      }
    ],
    "examples": [
      "!voicemaster limit [limit]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster limit"
  },
  "voicemaster_rename": {
    "raw_name": "rename",
    "func_name": "rename_vc",
    "parent_func_name": "voicemaster_group",
    "description": "rename your temporary voice channel",
    "aliases": [],
    "category": "utility",
    "permissions": [],
    "required_args": [],
    "optional_args": [
      {
        "name": "name",
        "type": "str"
      }
    ],
    "examples": [
      "!voicemaster rename [name]"
    ],
    "has_prefix": true,
    "has_slash": false,
    "is_group": false,
    "subcommands": [],
    "file_path": "C:\\Users\\bobby\\Downloads\\pybotv2\\plugins\\utility\\voicemaster.py",
    "name": "voicemaster rename"
  }
};