name: discord push diff

on:
  push:
    branches:
      - '**'

jobs:
  discord_push_diff:
    runs-on: ubuntu-latest
    steps:
      - name: send discord embed
        uses: bjd123/discord-webhook@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          embed: |
            {
              "title": "new push in ${{ github.repository }}",
              "url": "${{ github.event.compare }}",
              "color": 3447003,
              "author": {
                "name": "${{ github.actor }}",
                "url": "https://github.com/${{ github.actor }}"
              },
              "fields": [
                ${{ toJson(github.event.commits.map(commit => ({
                  name: commit.message.toLowerCase(),
                  value: [
                    commit.added.length > 0 ? "**added:**\n" + commit.added.map(f => `\`${f}\``).join("\n") : "",
                    commit.modified.length > 0 ? "**modified:**\n" + commit.modified.map(f => `\`${f}\``).join("\n") : "",
                    commit.removed.length > 0 ? "**removed:**\n" + commit.removed.map(f => `\`${f}\``).join("\n") : ""
                  ].filter(Boolean).join("\n"),
                  inline: false
                })))) }}
              ],
              "footer": {
                "text": "github actions"
              }
            }
